import { type GrammarScenario, grammarBatches, passeComposeVsImparfaitScenarios } from './grammarSessions'

export type GrammarTopic = {
  id: string
  /** Stored as the session topic; keep stable once sessions have been recorded. */
  topic: string
  title: string
  tagline: string
  level: string
  reminder: string
  rule: string
  reasonPlaceholder: string
  scenarios: GrammarScenario[]
  batches: { title: string; questionIds: number[] }[]
  outputPrompts: { zh: string; hint: string }[]
}

type Row = [
  prompt: string,
  a: string,
  b: string,
  correct: 'A' | 'B',
  explanation: string,
  translation: string,
  signal: string,
  vocabulary?: string[],
]

// Question ids are unique across topics (topic N starts at N * 100 + 1) because the server keys grammar errors by id.
const scenarios = (firstId: number, rows: Row[]): GrammarScenario[] =>
  rows.map(([prompt, a, b, correct, explanation, translation, signal, vocabulary], index) => ({
    id: firstId + index,
    prompt,
    options: [
      { label: 'A', text: a },
      { label: 'B', text: b },
    ],
    correct,
    explanation,
    translation,
    signal,
    ...(vocabulary ? { vocabulary } : {}),
  }))

const batchesFrom = (firstId: number, titles: [string, string, string]) => [
  { title: `第 1 组 · ${titles[0]}`, questionIds: [0, 1, 2, 3].map((offset) => firstId + offset) },
  { title: `第 2 组 · ${titles[1]}`, questionIds: [4, 5, 6, 7].map((offset) => firstId + offset) },
  { title: `第 3 组 · ${titles[2]}`, questionIds: [8, 9].map((offset) => firstId + offset) },
]

export const grammarTopics: GrammarTopic[] = [
  {
    id: 'passe-compose-imparfait',
    topic: 'passé composé vs imparfait',
    title: 'Passé composé vs imparfait',
    tagline: '过去时态恢复',
    level: 'A2–B1',
    reminder: '不要先找“时间词公式”。先问自己：这是在描述当时的背景/习惯，还是在讲发生并完成了什么？',
    rule: 'imparfait = 当时是什么样 / 正在干什么 / 以前经常干什么；passé composé = 发生了什么 / 完成了什么。',
    reasonPlaceholder: '例如：前面是在描述正在进行的背景，后面是突然发生的事件……',
    scenarios: passeComposeVsImparfaitScenarios,
    batches: grammarBatches,
    outputPrompts: [
      { zh: '我正在看电视的时候，我朋友给我打电话了。', hint: 'regarder la télé / appeler' },
      { zh: '以前我每天坐公交，但是昨天我走路去了公司。', hint: 'avant / prendre le bus / hier / aller au travail à pied' },
      { zh: '当我走进厨房的时候，我妈妈正在准备晚饭。', hint: 'entrer dans la cuisine / préparer le dîner' },
    ],
  },
  {
    id: 'subjonctif-indicatif',
    topic: 'subjonctif vs indicatif',
    title: 'Subjonctif vs indicatif',
    tagline: '虚拟式触发判断',
    level: 'B1–B2',
    reminder: '先问：主句是在陈述事实/确信，还是在表达意愿、情感、必要、怀疑？只有后者才触发 subjonctif。',
    rule: 'subjonctif = 意愿 / 情感 / 必要 / 怀疑 / 让步与目的（bien que、pour que）；indicatif = 事实与确信（penser que、espérer que、parce que）。',
    reasonPlaceholder: '例如：il faut que 表示必要，后面要用虚拟式……',
    scenarios: scenarios(101, [
      [
        'Il faut que tu ___ ce formulaire avant vendredi.',
        'remplisses',
        'remplis',
        'A',
        'il faut que 表示必要，后面的从句必须用 subjonctif：que tu remplisses。',
        '你必须在周五之前填好这张表。',
        'il faut que → subjonctif',
        ['remplir un formulaire = 填表'],
      ],
      [
        "Je pense qu'il ___ raison.",
        'ait',
        'a',
        'B',
        'penser que 用在肯定句里表示说话人的判断/确信，后面用 indicatif：il a raison。',
        '我认为他是对的。',
        '肯定的 penser que / croire que → indicatif',
        ['avoir raison = 有道理，是对的'],
      ],
      [
        "Je ne pense pas qu'elle ___ venir demain.",
        'puisse',
        'peut',
        'A',
        'penser que 一旦变成否定，就从“确信”变成“怀疑”，从句改用 subjonctif：qu’elle puisse。',
        '我不认为她明天能来。',
        'ne pas penser que / ne pas croire que → subjonctif',
      ],
      [
        "Bien qu'il ___ fatigué, il continue à travailler.",
        'est',
        'soit',
        'B',
        'bien que（虽然）表示让步，后面固定接 subjonctif：bien qu’il soit。',
        '虽然他很累，他还是继续工作。',
        'bien que / quoique → subjonctif',
        ['continuer à = 继续'],
      ],
      [
        'Je suis content que vous ___ là.',
        'soyez',
        'êtes',
        'A',
        'être content que 表达情感，情感 + que 的从句用 subjonctif：que vous soyez。',
        '我很高兴你们在这里。',
        '情感（content, triste, surpris…）+ que → subjonctif',
      ],
      [
        "J'espère que tu ___ bientôt.",
        'viennes',
        'viendras',
        'B',
        'espérer que 是经典陷阱：虽然是“希望”，但后面用 indicatif，通常是将来时：tu viendras。',
        '我希望你很快会来。',
        'espérer que → indicatif（常用 futur）',
        ['bientôt = 很快'],
      ],
      [
        "Elle veut que nous ___ à l'heure.",
        'arrivons',
        'arrivions',
        'B',
        'vouloir que 表达意愿，从句用 subjonctif：que nous arrivions（注意 nous 的虚拟式词尾 -ions）。',
        '她希望我们准时到。',
        'vouloir que / souhaiter que / demander que → subjonctif',
        ["à l'heure = 准时"],
      ],
      [
        'Il est certain que le train ___ en retard.',
        'est',
        'soit',
        'A',
        'il est certain que 表示确定的事实，用 indicatif。对比：il est possible que → subjonctif。',
        '可以肯定火车晚点了。',
        '确定（certain, sûr, évident）→ indicatif；可能/怀疑 → subjonctif',
        ['en retard = 迟到，晚点'],
      ],
      [
        "Je t'explique pour que tu ___ bien.",
        'comprennes',
        'comprends',
        'A',
        'pour que（为了让）表示目的，后面接 subjonctif：que tu comprennes。',
        '我给你解释，是为了让你好好理解。',
        'pour que / afin que → subjonctif',
        ['expliquer = 解释'],
      ],
      [
        "Parce qu'il ___ malade, il ne viendra pas.",
        'soit',
        'est',
        'B',
        'parce que 陈述一个真实的原因，用 indicatif。不要和 bien que（让步 → subjonctif）混淆。',
        '因为他病了，所以他不会来。',
        'parce que / puisque → indicatif',
        ['malade = 生病的'],
      ],
    ]),
    batches: batchesFrom(101, ['必要 / 确信 / 怀疑 / 让步', '情感、意愿与 espérer 陷阱', '目的与原因']),
    outputPrompts: [
      { zh: '我必须明天去银行。', hint: 'il faut que / aller à la banque' },
      { zh: '虽然下雨，我们还是出门了。', hint: 'bien que / pleuvoir / sortir' },
      { zh: '我希望你喜欢这个城市。', hint: 'espérer que（注意：不用虚拟式）/ aimer cette ville' },
    ],
  },
  {
    id: 'pronoms-complements',
    topic: 'pronoms COD / COI / y / en',
    title: 'Pronoms COD / COI / y / en',
    tagline: '宾语代词选择',
    level: 'A2–B1',
    reminder: '先还原动词后面本来接什么：直接接人或物，还是 à + 人、à + 地点/事物、de + 名词？介词决定代词。',
    rule: '直接宾语 → le / la / les；à + 人 → lui / leur；à + 地点或事物 → y；de + 名词或数量 → en。',
    reasonPlaceholder: '例如：téléphoner 后面是 à + 人，所以用间接宾语代词……',
    scenarios: scenarios(201, [
      [
        'Tu connais Marie ? — Oui, je ___ connais bien.',
        'la',
        'lui',
        'A',
        'connaître quelqu’un 直接接人，没有介词，所以用直接宾语代词 la。',
        '你认识玛丽吗？——认识，我跟她很熟。',
        '动词 + 人（无介词）→ le / la / les',
      ],
      [
        'Tu as téléphoné à tes parents ? — Oui, je ___ ai téléphoné hier.',
        'les',
        'leur',
        'B',
        'téléphoner à quelqu’un 带介词 à，所以用间接宾语代词；复数用 leur。',
        '你给父母打电话了吗？——打了，我昨天给他们打的。',
        '动词 + à + 人 → lui / leur',
        ['téléphoner à = 给……打电话'],
      ],
      [
        'Vous allez à Montréal ce week-end ? — Oui, nous ___ allons samedi.',
        'y',
        'en',
        'A',
        'à Montréal 是 à + 地点，用 y 代替。en 代替的是 de + 地点（从那里来）。',
        '你们这个周末去蒙特利尔吗？——去，我们周六去。',
        'à / dans / chez + 地点 → y',
      ],
      [
        "Tu veux du café ? — Non merci, je n'___ veux pas.",
        'le',
        'en',
        'B',
        'du café 是部分冠词 + 名词，用 en 代替。le 只能代替确指的东西（le café que tu as préparé）。',
        '你要咖啡吗？——不了谢谢，我不要。',
        'du / de la / des + 名词 → en',
      ],
      [
        "J'ai écrit à mon propriétaire. Je ___ ai demandé de réparer le chauffage.",
        'lui',
        "l'",
        'A',
        'demander quelque chose à quelqu’un：人前面有 à，用间接宾语代词 lui。',
        '我给房东写了信。我要求他修暖气。',
        'demander à / dire à / écrire à + 人 → lui / leur',
        ['le propriétaire = 房东', 'le chauffage = 暖气'],
      ],
      [
        'Ces documents, je ___ ai envoyés ce matin.',
        'leur',
        'les',
        'B',
        'envoyer quelque chose：documents 是直接宾语，用 les。注意直接宾语提前时过去分词要配合：envoyés。',
        '这些文件，我今天早上发出去了。',
        '直接宾语提前 → 过去分词配合（envoyés）',
        ['envoyer = 发送，寄'],
      ],
      [
        "Combien d'enfants avez-vous ? — J'___ ai deux.",
        'en',
        'les',
        'A',
        '带数量时用 en 代替名词，数词保留在句末：j’en ai deux。',
        '您有几个孩子？——我有两个。',
        '数量（deux, beaucoup, assez…）→ en + 数量',
      ],
      [
        "Tu penses à ton entrevue ? — Oui, j'___ pense tout le temps.",
        'en',
        'y',
        'B',
        'penser à quelque chose：à + 事物用 y 代替。注意 penser à + 人时要用 à lui / à elle。',
        '你在想你的面试吗？——是的，我一直在想。',
        'à + 事物 → y',
        ['une entrevue = 面试（魁北克用法）'],
      ],
      [
        'Elle a besoin de ce formulaire ? — Oui, elle ___ a besoin.',
        'en',
        'y',
        'A',
        'avoir besoin de quelque chose：de + 事物用 en 代替。',
        '她需要这张表吗？——是的，她需要。',
        'de + 事物（avoir besoin de, parler de, se servir de）→ en',
      ],
      [
        'Tu peux aider tes collègues ? — Oui, je peux ___ aider.',
        'leur',
        'les',
        'B',
        'aider quelqu’un 直接接人。中文“帮助他们”容易让人以为是间接宾语，但法语里没有 à，所以用 les。',
        '你能帮你的同事吗？——能，我可以帮他们。',
        'aider / remercier / écouter + 人（无介词）→ le / la / les',
        ['un collègue = 同事'],
      ],
    ]),
    batches: batchesFrom(201, ['直接 / 间接 / y / en 初判', '动词搭配决定代词', '容易受中文干扰的动词']),
    outputPrompts: [
      { zh: '这本书，我昨天读了它。', hint: 'ce livre / lire → je l’ai lu' },
      { zh: '我给她打了电话，但她没有回答我。', hint: 'téléphoner à / répondre à → lui / me' },
      { zh: '我去过那里两次，而且我还想再去。', hint: 'y aller / deux fois / vouloir y retourner' },
    ],
  },
  {
    id: 'hypothese-si',
    topic: 'hypothèse avec si',
    title: 'Hypothèse avec si',
    tagline: '条件句与条件式',
    level: 'B1–B2',
    reminder: 'si 后面永远不接 futur 或 conditionnel。先判断这个假设是真实可能、与现在相反，还是与过去相反。',
    rule: 'si + présent → futur / impératif；si + imparfait → conditionnel présent；si + plus-que-parfait → conditionnel passé。',
    reasonPlaceholder: '例如：这是与现在事实相反的假设，si 后面用 imparfait，主句用 conditionnel……',
    scenarios: scenarios(301, [
      [
        "Si j'ai le temps demain, je ___ à la bibliothèque.",
        'irai',
        'irais',
        'A',
        '真实可能发生的条件：si + présent，主句用 futur simple：j’irai。',
        '如果明天我有时间，我会去图书馆。',
        'si + présent → futur',
      ],
      [
        "Si j'avais plus d'argent, j'___ une maison.",
        'achèterai',
        'achèterais',
        'B',
        '与现在事实相反的假设：si + imparfait，主句用 conditionnel présent：j’achèterais。',
        '如果我有更多钱，我就会买一栋房子。',
        'si + imparfait → conditionnel présent',
      ],
      [
        "S'il ___ demain, nous resterons à la maison.",
        'pleut',
        'pleuvra',
        'A',
        '即使说的是明天，si 后面也不能用将来时，要用 présent：s’il pleut。',
        '如果明天下雨，我们就待在家里。',
        'si 之后不用 futur',
        ['rester à la maison = 待在家里'],
      ],
      [
        'Si tu ___ plus tôt, tu ne serais pas fatigué.',
        'te coucherais',
        'te couchais',
        'B',
        'si 后面不能用 conditionnel，要用 imparfait：si tu te couchais。conditionnel 只出现在主句。',
        '如果你早点睡，你就不会累了。',
        'si 之后不用 conditionnel',
        ['se coucher = 上床睡觉'],
      ],
      [
        "Si j'avais su, je ___ plus tôt.",
        'serais venu',
        'viendrai',
        'A',
        '与过去事实相反的假设：si + plus-que-parfait，主句用 conditionnel passé：je serais venu。',
        '如果我早知道，我就早点来了。',
        'si + plus-que-parfait → conditionnel passé',
      ],
      [
        "Si vous ___ des questions, n'hésitez pas à m'écrire.",
        'aurez',
        'avez',
        'B',
        '主句是命令式时，si 后面同样用 présent：si vous avez des questions。',
        '如果您有问题，请随时给我写信。',
        'si + présent → impératif',
        ['ne pas hésiter à = 不要犹豫'],
      ],
      [
        'À ta place, je ___ ce poste.',
        'accepterais',
        'accepterai',
        'A',
        'à ta place（如果我是你）本身就是一个与事实相反的假设，所以用 conditionnel：j’accepterais。',
        '如果我是你，我会接受这个职位。',
        'à ta place / à votre place → conditionnel',
        ['un poste = 职位'],
      ],
      [
        "Si elle avait étudié davantage, elle ___ l'examen.",
        'réussira',
        'aurait réussi',
        'B',
        'si + plus-que-parfait（avait étudié）说的是过去没发生的事，主句用 conditionnel passé：aurait réussi。',
        '如果她当时多学一点，她就通过考试了。',
        '与过去相反 → conditionnel passé',
        ['davantage = 更多'],
      ],
      [
        "Je ___ réserver une table pour deux, s'il vous plaît.",
        'voudrais',
        'voudrai',
        'A',
        'conditionnel 也用来表示礼貌的请求：je voudrais。voudrai 是将来时，不表示礼貌。',
        '我想订一张两人桌，谢谢。',
        '礼貌请求 → conditionnel（je voudrais, pourriez-vous）',
        ['réserver = 预订'],
      ],
      [
        'Si nous ___ au Québec, nous parlerions français tous les jours.',
        'vivrions',
        'vivions',
        'B',
        '主句 parlerions 是 conditionnel présent，对应的 si 从句用 imparfait：si nous vivions。',
        '如果我们住在魁北克，我们每天都会说法语。',
        '主句 conditionnel présent ← si + imparfait',
      ],
    ]),
    batches: batchesFrom(301, ['真实条件 vs 与现在相反', '与过去相反 / 命令式 / à ta place', '礼貌用法与综合判断']),
    outputPrompts: [
      { zh: '如果明天天气好，我们就去公园。', hint: 'si + présent → futur / faire beau / aller au parc' },
      { zh: '如果我是你，我会接受这份工作。', hint: 'si j’étais toi / accepter ce travail' },
      { zh: '如果我早知道，我就不会来了。', hint: 'si j’avais su / ne pas venir（conditionnel passé）' },
    ],
  },
  {
    id: 'pronoms-relatifs',
    topic: 'pronoms relatifs qui / que / dont / où',
    title: 'Pronoms relatifs : qui / que / dont / où',
    tagline: '关系从句连接',
    level: 'A2–B1',
    reminder: '看空格后面的从句缺什么：缺主语、缺直接宾语、动词带 de，还是缺地点/时间？',
    rule: '缺主语 → qui；缺直接宾语 → que；动词或形容词带 de → dont；地点或时间 → où。',
    reasonPlaceholder: '例如：空格后面直接是动词，从句缺主语，所以用 qui……',
    scenarios: scenarios(401, [
      [
        "C'est le collègue ___ m'a aidé hier.",
        'qui',
        'que',
        'A',
        '空格后面直接是动词 m’a aidé，从句缺主语，用 qui。',
        '这就是昨天帮了我的那位同事。',
        '空格后直接是动词 → qui',
      ],
      [
        "Le film ___ j'ai vu hier était excellent.",
        'qui',
        'que',
        'B',
        '从句已经有主语 je，缺的是 voir 的直接宾语，用 que。',
        '我昨天看的那部电影非常棒。',
        '空格后是“主语 + 动词” → que',
      ],
      [
        "C'est le quartier ___ j'habite depuis deux ans.",
        'où',
        'que',
        'A',
        'habiter dans un quartier：这里代替的是地点状语，用 où。',
        '这是我住了两年的街区。',
        '地点（habiter, travailler, aller）→ où',
        ['un quartier = 街区'],
      ],
      [
        "Voici le livre ___ je t'ai parlé.",
        'que',
        'dont',
        'B',
        'parler de quelque chose：动词带 de，用 dont。',
        '这就是我跟你说过的那本书。',
        'parler de / avoir besoin de / se souvenir de → dont',
      ],
      [
        'Le jour ___ je suis arrivé au Canada, il neigeait.',
        'où',
        'quand',
        'A',
        '时间名词（le jour, le moment, l’année）后面的关系代词用 où，不能用 quand。',
        '我到加拿大的那天，正在下雪。',
        '时间名词 + où',
      ],
      [
        "C'est une décision ___ je suis fier.",
        'que',
        'dont',
        'B',
        'être fier de quelque chose：形容词带 de，用 dont。',
        '这是一个让我感到自豪的决定。',
        'être fier de / content de / responsable de → dont',
        ['fier = 自豪的'],
      ],
      [
        "Les étudiants ___ ont réussi l'examen recevront un certificat.",
        'qui',
        'que',
        'A',
        '空格后面直接是动词 ont réussi，从句缺主语，用 qui。',
        '通过考试的学生将获得证书。',
        '空格后直接是动词 → qui',
        ['réussir un examen = 通过考试'],
      ],
      [
        'La lettre ___ tu as écrite est très claire.',
        'dont',
        'que',
        'B',
        'écrire quelque chose 直接接宾语，用 que。因为直接宾语提前，过去分词配合成 écrite。',
        '你写的那封信非常清楚。',
        'que + 过去分词配合（écrite）',
      ],
      [
        "C'est l'outil ___ j'ai besoin pour ce travail.",
        'dont',
        'que',
        'A',
        'avoir besoin de quelque chose：带 de，用 dont。',
        '这是我做这项工作需要的工具。',
        'avoir besoin de → dont',
        ['un outil = 工具'],
      ],
      [
        "La ville ___ nous avons visitée l'été dernier est magnifique.",
        'où',
        'que',
        'B',
        '虽然先行词是地点，但 visiter 直接接宾语（visiter une ville），所以用 que，而不是 où。',
        '我们去年夏天参观的那座城市非常美。',
        '先行词是地点 ≠ 一定用 où，要看动词是否直接接宾语',
      ],
    ]),
    batches: batchesFrom(401, ['qui / que / où / dont 初判', '时间名词与带 de 的搭配', '综合判断']),
    outputPrompts: [
      { zh: '这是我昨天买的电脑。', hint: 'l’ordinateur / que / acheter' },
      { zh: '我有一个住在魁北克的朋友。', hint: 'un ami / qui / habiter à Québec' },
      { zh: '这是我需要的文件。', hint: 'le document / dont / avoir besoin de' },
    ],
  },
]

export const defaultGrammarTopic = grammarTopics[0]

export const findGrammarTopic = (id: string | null | undefined) => grammarTopics.find((topic) => topic.id === id)

/** A synced draft carries no topic id; recover it from the question ids it has touched. */
export const grammarTopicForQuestionIds = (ids: string[]) =>
  grammarTopics.find((topic) => ids.some((id) => topic.scenarios.some((scenario) => String(scenario.id) === id)))
