import type { TcfQuestion } from './tcfMock'

// Second full CO/CE set. Like set A, questions run from A1 (Q1) up to C1–C2 (Q39).
type Row = [
  type: string,
  source: string,
  prompt: string,
  choices: [string, string, string, string],
  answer: 0 | 1 | 2 | 3,
  explanation: string,
]

const build = (prefix: 'co' | 'ce', rows: Row[]): TcfQuestion[] =>
  rows.map(([type, source, prompt, choices, answer, explanation], index) => ({
    id: `${prefix}-b${String(index + 1).padStart(2, '0')}`,
    type,
    prompt,
    choices,
    answer,
    explanation,
    ...(prefix === 'co' ? { audioText: source } : { passage: source }),
  }))

export const TCF_LISTENING_SET_B: TcfQuestion[] = build('co', [
  [
    'dialogue',
    "— Bonjour, un café et un croissant, s'il vous plaît. — Sur place ou à emporter ? — À emporter, merci.",
    'Que commande le client ?',
    ['Un thé et un gâteau', 'Un sandwich à emporter', 'Un café et un croissant', 'Un jus d’orange'],
    2,
    'Le client demande un café et un croissant.',
  ],
  [
    'announcement',
    'Chers clients, le magasin fermera ses portes dans quinze minutes. Merci de vous diriger vers les caisses.',
    'Que doivent faire les clients ?',
    ['Aller payer leurs achats', 'Attendre l’ouverture', 'Changer d’étage', 'Rapporter un article'],
    0,
    'On leur demande de se diriger vers les caisses avant la fermeture.',
  ],
  [
    'voicemail',
    "Salut Karim, c'est Julie. Je serai en retard ce soir, mon autobus est en panne. Commencez à manger sans moi.",
    'Pourquoi Julie sera-t-elle en retard ?',
    ['Elle travaille tard', 'Elle a oublié le rendez-vous', 'Elle est malade', 'Son autobus est en panne'],
    3,
    'Julie explique que son autobus est en panne.',
  ],
  [
    'dialogue',
    "— Excusez-moi, la bibliothèque est loin d'ici ? — Non, continuez tout droit et tournez à gauche après la pharmacie.",
    'Que cherche la personne ?',
    ['Une pharmacie', 'La bibliothèque', 'Un arrêt d’autobus', 'Un restaurant'],
    1,
    'Elle demande où se trouve la bibliothèque; la pharmacie n’est qu’un repère.',
  ],
  [
    'announcement',
    'Demain, il neigera toute la journée sur la région de Québec, avec des températures autour de moins dix degrés.',
    'Quel temps fera-t-il demain ?',
    ['Il pleuvra', 'Il fera chaud', 'Il neigera', 'Il y aura du brouillard'],
    2,
    'Le bulletin annonce de la neige toute la journée.',
  ],
  [
    'dialogue',
    "— Tu viens à la piscine samedi ? — Désolé, je garde mon petit frère samedi. Dimanche, c'est possible ?",
    'Que propose le garçon ?',
    ['D’y aller dimanche', 'D’annuler la sortie', 'D’amener son frère', 'D’y aller samedi soir'],
    0,
    'Il n’est pas libre samedi et propose dimanche.',
  ],
  [
    'voicemail',
    'Bonjour, ici le cabinet dentaire Lavoie. Votre rendez-vous de jeudi est déplacé à vendredi, à la même heure. Merci de nous rappeler pour confirmer.',
    "Qu'est-ce qui change ?",
    ['L’heure du rendez-vous', 'Le nom du dentiste', 'L’adresse du cabinet', 'Le jour du rendez-vous'],
    3,
    'Le rendez-vous passe de jeudi à vendredi, à la même heure.',
  ],
  [
    'dialogue',
    '— Je voudrais envoyer ce colis en France. — Par avion, ça coûte vingt-deux dollars et il arrive dans une semaine.',
    'Où se passe cette conversation ?',
    ['À l’aéroport', 'Au bureau de poste', 'Dans une agence de voyages', 'À la banque'],
    1,
    'On envoie un colis : la scène se passe au bureau de poste.',
  ],
  [
    'announcement',
    "Les passagers du vol 418 pour Vancouver sont priés de se présenter à la porte B6. L'embarquement commence dans dix minutes.",
    'Que doivent faire les passagers ?',
    ['Récupérer leurs bagages', 'Changer de vol', 'Aller à la porte d’embarquement', 'Attendre dix heures'],
    2,
    'Ils doivent se présenter à la porte B6 pour embarquer.',
  ],
  [
    'dialogue',
    '— Cet appartement vous plaît ? — Oui, il est lumineux, mais le loyer est trop élevé pour moi.',
    'Quel est le problème ?',
    ['Le prix du loyer', 'Le manque de lumière', 'La taille des pièces', 'Le bruit des voisins'],
    0,
    'L’appartement plaît, mais le loyer est trop élevé.',
  ],
  [
    'dialogue',
    "— Tu as trouvé un emploi d'été ? — Oui, je vais travailler dans un camp de jour. Ce n'est pas très bien payé, mais j'adore m'occuper des enfants.",
    'Pourquoi a-t-elle accepté cet emploi ?',
    [
      'Pour le salaire',
      'Parce que c’est près de chez elle',
      'Parce qu’elle n’avait pas le choix',
      'Parce qu’elle aime travailler avec les enfants',
    ],
    3,
    'Elle reconnaît que le salaire est faible, mais elle adore s’occuper des enfants.',
  ],
  [
    'voicemail',
    "Bonjour, c'est le garage Tremblay. Votre voiture est prête, mais nous avons dû remplacer les freins. La facture sera donc plus élevée que prévu.",
    "Qu'annonce le garagiste ?",
    ['La voiture n’est pas réparée', 'Le coût sera plus élevé', 'Le garage sera fermé', 'Il faut racheter une voiture'],
    1,
    'Le remplacement des freins augmente le montant de la facture.',
  ],
  [
    'news',
    'En raison de travaux, la station de métro Jean-Talon sera fermée cette fin de semaine. Un service de navettes par autobus sera offert gratuitement.',
    'Quelle solution est proposée aux usagers ?',
    ['Des taxis remboursés', 'Un billet à moitié prix', 'Des autobus de remplacement', 'Une autre ligne de métro'],
    2,
    'Des navettes gratuites par autobus remplacent le métro.',
  ],
  [
    'dialogue',
    "— J'hésite entre le cours du soir et le cours en ligne. — Avec ton horaire de travail qui change tout le temps, le cours en ligne serait plus pratique.",
    'Quel conseil est donné ?',
    ['Choisir le cours en ligne', 'Changer d’emploi', 'Abandonner les études', 'Suivre les deux cours'],
    0,
    'À cause de l’horaire variable, le cours en ligne est jugé plus pratique.',
  ],
  [
    'announcement',
    'La bibliothèque rappelle que les documents rendus en retard entraînent une amende de vingt-cinq sous par jour. Vous pouvez renouveler vos emprunts en ligne.',
    'Comment éviter une amende ?',
    ['En payant à l’avance', 'En empruntant moins de livres', 'En venant le matin', 'En renouvelant ses emprunts à temps'],
    3,
    'Le renouvellement en ligne permet d’éviter le retard, donc l’amende.',
  ],
  [
    'dialogue',
    "— Alors, ce nouveau quartier ? — C'est calme et les voisins sont sympathiques. Le seul inconvénient, c'est qu'il n'y a aucune épicerie à proximité.",
    'De quoi se plaint la personne ?',
    ['Du bruit', 'Du manque de commerces', 'Des voisins', 'Du prix des maisons'],
    1,
    'Le seul inconvénient cité est l’absence d’épicerie à proximité.',
  ],
  [
    'news',
    "Le festival de jazz a attiré plus de cent mille visiteurs cette année, soit le double de l'an dernier, grâce notamment aux concerts gratuits en plein air.",
    "Qu'apprend-on sur le festival ?",
    ['Il a été annulé', 'Il est devenu payant', 'Sa fréquentation a doublé', 'Il a changé de ville'],
    2,
    'Le nombre de visiteurs est le double de celui de l’an dernier.',
  ],
  [
    'dialogue',
    "— Vous avez de l'expérience en service à la clientèle ? — J'ai travaillé trois ans dans un centre d'appels, où je formais aussi les nouveaux employés.",
    'Dans quel contexte a lieu cet échange ?',
    ['Un entretien d’embauche', 'Une réclamation', 'Une réunion de famille', 'Un cours de langue'],
    0,
    'On interroge un candidat sur son expérience : c’est un entretien d’embauche.',
  ],
  [
    'opinion',
    "Moi, j'ai arrêté de prendre la voiture pour aller au bureau. À vélo, je mets dix minutes de plus, mais j'arrive détendu et je fais de l'exercice.",
    'Quel avantage du vélo est mentionné ?',
    ['Il est plus rapide', 'Il coûte moins cher', 'Il évite la pluie', 'Il permet d’arriver détendu'],
    3,
    'Le trajet est plus long, mais la personne arrive détendue et fait de l’exercice.',
  ],
  [
    'message',
    "Bonjour, c'est la propriétaire. Le plombier passera mardi entre neuf heures et midi pour réparer la fuite. Pourriez-vous lui laisser l'accès à la salle de bain ?",
    'Que demande la propriétaire ?',
    ['De payer le plombier', 'De permettre l’accès au logement', 'De quitter l’appartement', 'De réparer la fuite soi-même'],
    1,
    'Elle demande de laisser le plombier accéder à la salle de bain.',
  ],
  [
    'news',
    "Selon une enquête récente, près d'un travailleur sur trois préférerait conserver le télétravail au moins deux jours par semaine, même si cela impliquait de renoncer à une augmentation de salaire.",
    "Que révèle l'enquête ?",
    [
      'Les travailleurs veulent tous revenir au bureau',
      'Le télétravail est jugé inefficace',
      'Beaucoup tiennent au télétravail, même au prix d’un salaire moindre',
      'Les salaires ont augmenté',
    ],
    2,
    'Un tiers des travailleurs renoncerait à une augmentation pour garder le télétravail.',
  ],
  [
    'dialogue',
    "— On pourrait reporter le lancement du produit d'un mois. — Ce serait risqué : nos concurrents sortent le leur en mars. Je préfère lancer une version simplifiée à la date prévue.",
    'Que préfère la deuxième personne ?',
    ['Lancer à temps une version réduite', 'Reporter le lancement', 'Annuler le projet', 'Attendre les concurrents'],
    0,
    'Elle veut respecter la date prévue avec une version simplifiée.',
  ],
  [
    'opinion',
    "On reproche souvent aux jeunes de passer trop de temps sur leur téléphone. Pourtant, bien des adultes font exactement la même chose à table. Avant de donner des leçons, commençons par donner l'exemple.",
    "Quelle est l'idée principale ?",
    [
      'Les jeunes lisent trop peu',
      'Les téléphones devraient être interdits',
      'Les adultes utilisent moins leur téléphone',
      'Les adultes devraient d’abord montrer l’exemple',
    ],
    3,
    'La personne invite les adultes à donner l’exemple avant de critiquer les jeunes.',
  ],
  [
    'news',
    "La municipalité offrira dès l'automne une subvention pouvant atteindre cinq cents dollars aux résidents qui remplacent leur chauffage au mazout par un système électrique.",
    "À qui s'adresse la subvention ?",
    [
      'Aux entreprises de chauffage',
      'Aux résidents qui changent de système de chauffage',
      'Aux nouveaux arrivants',
      'Aux propriétaires de voitures électriques',
    ],
    1,
    'Elle vise les résidents qui remplacent le mazout par un système électrique.',
  ],
  [
    'dialogue',
    "— Ton exposé était clair, mais tu as dépassé le temps de cinq minutes. — Je sais, j'ai voulu trop en dire. — La prochaine fois, garde seulement trois idées principales.",
    'Quel reproche est fait ?',
    ['L’exposé manquait de clarté', 'Le sujet était mal choisi', 'L’exposé était trop long', 'Il n’y avait pas d’exemples'],
    2,
    'L’exposé était clair, mais il a dépassé le temps prévu.',
  ],
  [
    'opinion',
    'Je ne suis pas contre les voitures électriques, mais présenter cette technologie comme une solution miracle me semble naïf : il faut aussi repenser nos déplacements et investir dans le transport collectif.',
    'Quelle est la position de la personne ?',
    [
      'La voiture électrique ne suffit pas à elle seule',
      'La voiture électrique est inutile',
      'Le transport collectif coûte trop cher',
      'Il faut interdire les voitures',
    ],
    0,
    'Elle n’y est pas opposée, mais refuse d’y voir une solution miracle.',
  ],
  [
    'news',
    "Faute de personnel, l'urgence de l'hôpital régional sera fermée la nuit pendant tout l'été. Les patients seront dirigés vers l'établissement le plus proche, à quarante kilomètres.",
    'Pourquoi le service est-il réduit ?',
    ['À cause de travaux', 'En raison d’une épidémie', 'Par manque de patients', 'Par manque d’employés'],
    3,
    '« Faute de personnel » signifie qu’il manque d’employés.',
  ],
  [
    'dialogue',
    "— Je pensais m'inscrire à ce programme de mentorat. — Excellente idée. Moi, c'est mon mentor qui m'a aidée à comprendre le marché du travail d'ici et à me bâtir un réseau.",
    'Que pense la femme du mentorat ?',
    [
      'C’est une perte de temps',
      'C’est très utile pour s’intégrer professionnellement',
      'C’est réservé aux étudiants',
      'C’est trop coûteux',
    ],
    1,
    'Son mentor l’a aidée à comprendre le marché du travail et à bâtir un réseau.',
  ],
  [
    'opinion',
    "Certes, les achats en ligne sont pratiques. Mais quand une librairie de quartier ferme, ce n'est pas seulement un commerce qui disparaît, c'est aussi un lieu de rencontre et de conseil.",
    'Que regrette la personne ?',
    ['Le prix des livres', 'La lenteur des livraisons', 'La disparition d’un lieu de vie local', 'Le manque de choix en ligne'],
    2,
    'Elle regrette la perte d’un lieu de rencontre et de conseil.',
  ],
  [
    'news',
    "Le taux de chômage a légèrement reculé le mois dernier. Toutefois, les économistes soulignent que cette baisse s'explique surtout par la création d'emplois à temps partiel.",
    'Quelle nuance les économistes apportent-ils ?',
    [
      'La baisse repose surtout sur des emplois à temps partiel',
      'Le chômage a fortement augmenté',
      'Les salaires ont doublé',
      'Les chiffres sont faux',
    ],
    0,
    'La baisse du chômage vient surtout d’emplois à temps partiel.',
  ],
  [
    'opinion',
    "Qu'on le veuille ou non, l'intelligence artificielle va transformer l'enseignement. La question n'est donc plus de savoir s'il faut l'autoriser en classe, mais comment apprendre aux élèves à s'en servir avec esprit critique.",
    'Selon la personne, quel est le véritable enjeu ?',
    ['Interdire ces outils à l’école', 'Remplacer les enseignants', 'Réduire le nombre d’élèves', 'Former les élèves à un usage critique'],
    3,
    'La question n’est plus d’autoriser ou non, mais d’apprendre à s’en servir avec esprit critique.',
  ],
  [
    'dialogue',
    "— Votre roman se déroule dans un village minier. Est-ce autobiographique ? — Pas vraiment. Je me suis inspirée des récits de mon grand-père, mais les personnages sont inventés. Disons que le décor est vrai et que l'histoire est fausse.",
    "Que dit l'auteure de son roman ?",
    ['Tout y est réel', 'Le cadre est réel, mais l’intrigue est fictive', 'Elle a vécu dans ce village', 'Son grand-père en est le héros'],
    1,
    '« Le décor est vrai et l’histoire est fausse » : seul le cadre est réel.',
  ],
  [
    'news',
    "Le projet de loi sur le logement a été adopté hier, non sans avoir été amendé à plusieurs reprises. L'opposition, qui réclamait un gel des loyers, a dénoncé une réforme qu'elle juge largement insuffisante.",
    "Quelle est la réaction de l'opposition ?",
    [
      'Elle salue la réforme',
      'Elle a retiré ses demandes',
      'Elle estime que la loi ne va pas assez loin',
      'Elle a obtenu le gel des loyers',
    ],
    2,
    'L’opposition juge la réforme largement insuffisante.',
  ],
  [
    'opinion',
    "On vante la flexibilité des emplois à la demande, mais cette liberté a un prix : sans congés payés ni assurance, c'est le travailleur qui assume tous les risques que l'entreprise ne veut plus porter.",
    'Quelle critique est formulée ?',
    [
      'Les risques sont transférés aux travailleurs',
      'Ces emplois sont trop rigides',
      'Les entreprises paient trop d’assurances',
      'Les travailleurs refusent la flexibilité',
    ],
    0,
    'Le travailleur assume les risques que l’entreprise ne porte plus.',
  ],
  [
    'dialogue',
    "— Les ventes ont progressé de huit pour cent. — Avant de se réjouir, il faudrait savoir si c'est dû à notre campagne ou simplement à la fermeture de notre concurrent principal.",
    'Que suggère la deuxième personne ?',
    ['D’arrêter la campagne', 'De fêter le résultat', 'De racheter le concurrent', 'De vérifier la cause réelle de la hausse'],
    3,
    'Elle veut savoir si la hausse vient de la campagne ou de la fermeture du concurrent.',
  ],
  [
    'opinion',
    "Je trouve paradoxal qu'on demande aux citoyens de réduire leur consommation d'eau alors que les réseaux municipaux en perdent près du tiers à cause de fuites jamais réparées.",
    'Quel paradoxe la personne souligne-t-elle ?',
    [
      'L’eau est trop chère',
      'On sollicite les citoyens alors que le réseau gaspille',
      'Les citoyens refusent tout effort',
      'Les fuites ont été réparées',
    ],
    1,
    'On demande un effort aux citoyens alors que le réseau perd un tiers de l’eau.',
  ],
  [
    'news',
    "Une étude menée auprès de deux mille adolescents établit un lien entre le manque de sommeil et la baisse des résultats scolaires. Les chercheurs précisent cependant qu'ils ne peuvent pas affirmer que l'un cause l'autre.",
    'Quelle prudence les chercheurs expriment-ils ?',
    [
      'L’échantillon est trop petit',
      'Les adolescents ont menti',
      'Le lien observé ne prouve pas une causalité',
      'Le sommeil n’a aucun effet',
    ],
    2,
    'Ils observent un lien, sans pouvoir affirmer une relation de cause à effet.',
  ],
  [
    'opinion',
    "Plutôt que de multiplier les campagnes de sensibilisation, dont l'effet s'estompe en quelques semaines, mieux vaudrait aménager les rues de façon à ce que la vitesse excessive devienne tout simplement impossible.",
    'Que privilégie la personne ?',
    ['Modifier l’aménagement des rues', 'Augmenter les campagnes', 'Supprimer les limites de vitesse', 'Punir davantage les piétons'],
    0,
    'Elle préfère un aménagement des rues qui rend la vitesse impossible.',
  ],
  [
    'news',
    "Le musée a finalement renoncé à vendre une partie de sa collection pour combler son déficit. Face au tollé suscité par l'annonce, la direction mise désormais sur une campagne de dons et sur l'ouverture en soirée.",
    'Pourquoi le musée a-t-il changé de stratégie ?',
    ['Le déficit a disparu', 'La collection a été volée', 'Les dons étaient trop nombreux', 'L’annonce a provoqué de vives protestations'],
    3,
    '« Le tollé » désigne les vives protestations qui ont suivi l’annonce.',
  ],
])

export const TCF_READING_SET_B: TcfQuestion[] = build('ce', [
  [
    'notice',
    'Boulangerie Au Bon Pain — Ouvert du mardi au dimanche, de 6 h 30 à 18 h. Fermé le lundi.',
    'Quel jour la boulangerie est-elle fermée ?',
    ['Le lundi', 'Le mardi', 'Le dimanche', 'Le samedi'],
    0,
    'L’affiche précise : « Fermé le lundi ».',
  ],
  [
    'message',
    "Maman, je rentre tard ce soir : j'ai un entraînement de soccer jusqu'à 19 h. Garde-moi une assiette ! — Théo",
    'Que demande Théo ?',
    ['Qu’on vienne le chercher', 'Qu’on l’inscrive au soccer', 'Qu’on lui garde à manger', 'Qu’on l’appelle à 19 h'],
    2,
    '« Garde-moi une assiette » : il veut qu’on lui garde son repas.',
  ],
  [
    'notice',
    "Ascenseur en panne. Veuillez utiliser l'escalier situé au fond du couloir. Réparation prévue demain matin.",
    'Que doivent faire les résidents ?',
    ['Attendre demain', 'Appeler le réparateur', 'Rester chez eux', 'Prendre l’escalier'],
    3,
    'L’avis demande d’utiliser l’escalier au fond du couloir.',
  ],
  [
    'short-text',
    'À vendre : vélo de montagne pour adulte, très bon état, casque inclus. 120 $. Appelez Marc après 18 h au 555-0142.',
    "Qu'est-ce qui est offert avec le vélo ?",
    ['Un cadenas', 'Un casque', 'Une pompe', 'Une livraison gratuite'],
    1,
    'L’annonce indique « casque inclus ».',
  ],
  [
    'practical',
    "Recette express : faites cuire les pâtes 10 minutes. Pendant ce temps, faites revenir l'ail dans l'huile d'olive. Mélangez, ajoutez le fromage et servez chaud.",
    'Que fait-on pendant la cuisson des pâtes ?',
    ['On fait revenir l’ail', 'On râpe le fromage', 'On met la table', 'On ajoute la sauce tomate'],
    0,
    '« Pendant ce temps, faites revenir l’ail dans l’huile d’olive. »',
  ],
  [
    'message',
    "Bonjour à tous, la réunion d'équipe de 14 h est reportée à demain 10 h, salle B. Merci d'apporter vos rapports mensuels. — Nadia",
    'Que doivent apporter les employés ?',
    ['Leur ordinateur', 'Leur dîner', 'Leurs rapports mensuels', 'Leur horaire'],
    2,
    'Nadia demande d’apporter les rapports mensuels.',
  ],
  [
    'notice',
    "Parc des Érables : les chiens sont admis uniquement en laisse. Baignade interdite dans l'étang. Merci de jeter vos déchets dans les poubelles.",
    "Qu'est-ce qui est interdit ?",
    ['Promener un chien en laisse', 'Pique-niquer', 'Utiliser les poubelles', 'Se baigner dans l’étang'],
    3,
    'Le panneau indique « Baignade interdite dans l’étang ».',
  ],
  [
    'short-text',
    'Cours de français gratuits pour adultes, tous les mardis et jeudis de 18 h à 20 h au centre communautaire. Inscription obligatoire avant le 15 septembre.',
    'Que faut-il faire pour participer ?',
    ['Payer des frais', 'S’inscrire avant une date limite', 'Passer un examen', 'Venir le samedi'],
    1,
    'Les cours sont gratuits, mais l’inscription est obligatoire avant le 15 septembre.',
  ],
  [
    'email',
    "Madame, nous avons bien reçu votre commande n° 4521. Elle sera expédiée sous 48 heures. Vous recevrez un courriel contenant le numéro de suivi dès l'envoi du colis.",
    "Que recevra la cliente au moment de l'envoi ?",
    ['Un numéro de suivi', 'Un remboursement', 'Un catalogue', 'Une facture papier'],
    0,
    'Un courriel avec le numéro de suivi sera envoyé à l’expédition.',
  ],
  [
    'practical',
    'Carte mensuelle de transport : 94 $ tarif régulier, 56 $ tarif étudiant (carte étudiante valide exigée). Gratuit pour les enfants de moins de 12 ans accompagnés.',
    'Qui doit présenter une preuve pour obtenir un rabais ?',
    ['Les enfants', 'Les aînés', 'Les étudiants', 'Les touristes'],
    2,
    'Le tarif étudiant exige une carte étudiante valide.',
  ],
  [
    'email',
    "Bonjour Monsieur Roy, je vous écris au sujet du logement de la rue Cartier. Je suis intéressée, mais j'aimerais savoir si le chauffage est compris dans le loyer et si les animaux sont acceptés. Pourrais-je le visiter cette semaine ? Cordialement, Amina Diallo",
    'Pourquoi Amina écrit-elle ?',
    [
      'Pour annuler une visite',
      'Pour signaler un problème de chauffage',
      'Pour résilier son bail',
      'Pour obtenir des précisions sur un logement',
    ],
    3,
    'Elle pose des questions sur le chauffage et les animaux, et demande une visite.',
  ],
  [
    'article',
    'De plus en plus de familles choisissent de passer leurs vacances près de chez elles. Outre les économies réalisées, elles disent redécouvrir leur propre région et éviter la fatigue des longs trajets.',
    "Quel avantage n'est PAS mentionné ?",
    ['Dépenser moins', 'Rencontrer des touristes étrangers', 'Mieux connaître sa région', 'Éviter les longs déplacements'],
    1,
    'Le texte cite les économies, la redécouverte de la région et les trajets courts, pas les touristes étrangers.',
  ],
  [
    'notice',
    "Avis aux locataires : l'eau sera coupée jeudi de 9 h à 15 h en raison du remplacement d'une conduite. Nous vous conseillons de faire des réserves d'eau la veille.",
    'Que recommande-t-on aux locataires ?',
    ['De prévoir de l’eau à l’avance', 'De quitter l’immeuble', 'D’appeler un plombier', 'De fermer leur chauffage'],
    0,
    'L’avis conseille de faire des réserves d’eau la veille.',
  ],
  [
    'short-text',
    "Offre d'emploi — Le Café du Port recherche un serveur ou une serveuse à temps partiel, soirs et fins de semaine. Expérience souhaitée mais non exigée. Bilinguisme français-anglais indispensable.",
    'Quelle condition est obligatoire ?',
    ['Avoir de l’expérience', 'Travailler à temps plein', 'Parler français et anglais', 'Être disponible le matin'],
    2,
    'L’expérience est seulement souhaitée; le bilinguisme est indispensable.',
  ],
  [
    'article',
    "Depuis qu'elle a installé des ruches sur son toit, l'école Saint-Louis utilise le miel récolté pour financer ses sorties éducatives. Les élèves participent à la récolte et apprennent le rôle des abeilles dans la nature.",
    'À quoi sert le miel récolté ?',
    ['À nourrir les élèves à la cafétéria', 'À payer les enseignants', 'À remplacer le sucre', 'À financer des sorties scolaires'],
    3,
    'Le miel sert à financer les sorties éducatives.',
  ],
  [
    'email',
    "Chère cliente, votre abonnement au centre sportif arrive à échéance le 30 juin. Si vous le renouvelez avant cette date, vous bénéficierez de deux mois gratuits. Passé ce délai, le tarif régulier s'appliquera.",
    'Comment obtenir les deux mois gratuits ?',
    ['En parrainant un ami', 'En renouvelant avant le 30 juin', 'En payant le tarif régulier', 'En changeant de centre'],
    1,
    'L’offre vaut pour un renouvellement fait avant le 30 juin.',
  ],
  [
    'opinion',
    "À mon avis, les devoirs à la maison devraient être limités au primaire. Après six heures de classe, les enfants ont besoin de jouer et de bouger. Mieux vaut lire vingt minutes avec plaisir que remplir des pages d'exercices.",
    "Que propose l'auteur ?",
    ['De réduire les devoirs au primaire', 'D’allonger la journée d’école', 'De supprimer la lecture', 'D’ajouter des exercices'],
    0,
    'L’auteur veut limiter les devoirs au primaire et privilégier la lecture plaisir.',
  ],
  [
    'practical',
    "Politique de retour : les articles peuvent être retournés dans les 30 jours suivant l'achat, sur présentation du reçu. Les articles soldés sont échangeables, mais non remboursables.",
    'Que peut-on faire avec un article acheté en solde ?',
    ['Obtenir un remboursement', 'Le retourner sans reçu', 'L’échanger', 'Le retourner après 60 jours'],
    2,
    'Les articles soldés sont échangeables, mais non remboursables.',
  ],
  [
    'article',
    'La ville de Sherbrooke teste un service de bibliothèque mobile : un autobus rempli de livres se rend chaque semaine dans les quartiers éloignés. Le projet vise surtout les aînés et les familles sans voiture.',
    'À qui ce service est-il principalement destiné ?',
    ['Aux étudiants universitaires', 'Aux touristes', 'Aux libraires', 'Aux personnes ayant du mal à se déplacer'],
    3,
    'Il vise les aînés et les familles sans voiture, donc ceux qui se déplacent difficilement.',
  ],
  [
    'message',
    "J'ai suivi la formation en comptabilité à distance l'an dernier. Le contenu est solide, mais il faut être très discipliné : personne ne vous rappelle les échéances. Je la recommande aux personnes autonomes.",
    "Quelle réserve l'auteur exprime-t-il ?",
    ['Le contenu est faible', 'La formation exige beaucoup d’autonomie', 'Les frais sont trop élevés', 'Les professeurs sont absents'],
    1,
    'Le contenu est jugé solide; la réserve porte sur la discipline personnelle requise.',
  ],
  [
    'article',
    'Longtemps boudés, les marchés publics connaissent un regain de popularité. Les consommateurs y cherchent des produits frais, mais aussi un contact direct avec les producteurs. Pour ces derniers, vendre sans intermédiaire permet de conserver une plus grande part du prix payé.',
    'Quel bénéfice les producteurs tirent-ils des marchés publics ?',
    [
      'Une meilleure marge grâce à la vente directe',
      'Des subventions de l’État',
      'Moins d’heures de travail',
      'Des prix imposés par la ville',
    ],
    0,
    'Sans intermédiaire, ils conservent une plus grande part du prix payé.',
  ],
  [
    'opinion',
    "Interdire les cellulaires en classe ne réglera pas tout. Certes, l'attention des élèves s'améliorera peut-être, mais l'école a aussi le devoir de leur apprendre à maîtriser ces outils qu'ils utiliseront toute leur vie.",
    "Quelle est la position de l'auteur ?",
    [
      'L’interdiction est une solution complète',
      'Les cellulaires n’ont aucun effet sur l’attention',
      'L’interdiction ne suffit pas : il faut aussi éduquer',
      'L’école ne doit pas s’occuper de technologie',
    ],
    2,
    'L’auteur admet un effet possible sur l’attention, mais réclame aussi une éducation à ces outils.',
  ],
  [
    'article',
    "Une entreprise de Québec a adopté la semaine de quatre jours sans réduire les salaires. Après un an, la direction constate une productivité stable, une baisse de l'absentéisme et beaucoup plus de candidatures lors des recrutements.",
    "Quel effet n'a PAS été observé ?",
    ['Moins d’absences', 'Un recrutement plus facile', 'Une productivité maintenue', 'Une diminution des salaires'],
    3,
    'La semaine de quatre jours a été adoptée sans réduire les salaires.',
  ],
  [
    'email',
    "Madame, Monsieur, j'ai été facturé deux fois pour mon forfait du mois de mars. Malgré deux appels à votre service à la clientèle, l'erreur n'a toujours pas été corrigée. Je vous demande de procéder au remboursement dans les dix jours, faute de quoi je déposerai une plainte auprès de l'Office de la protection du consommateur.",
    "Que fera le client si sa demande n'est pas satisfaite ?",
    ['Il changera de forfait', 'Il portera plainte', 'Il rappellera le service', 'Il paiera une troisième fois'],
    1,
    '« Faute de quoi je déposerai une plainte » : il portera plainte.',
  ],
  [
    'article',
    "Les jardins communautaires ne servent pas qu'à produire des légumes. Selon une étude, ils brisent l'isolement des personnes âgées et favorisent les échanges entre voisins d'origines différentes. Plusieurs villes peinent toutefois à répondre à la demande : les listes d'attente dépassent parfois trois ans.",
    'Quel problème est signalé ?',
    ['Le manque de parcelles disponibles', 'La mauvaise qualité des légumes', 'Les conflits entre voisins', 'Le désintérêt des aînés'],
    0,
    'Les villes ne répondent pas à la demande : les listes d’attente dépassent trois ans.',
  ],
  [
    'opinion',
    "On présente souvent le bénévolat comme un geste purement généreux. En réalité, ceux qui s'engagent y gagnent aussi : nouvelles compétences, réseau de contacts, sentiment d'utilité. Il n'y a rien de honteux à le reconnaître ; c'est même ce qui rend l'engagement durable.",
    "Selon l'auteur, les avantages personnels du bénévolat sont…",
    ['une raison d’y renoncer', 'un secret à cacher', 'une motivation légitime', 'sans importance'],
    2,
    'Il n’y a « rien de honteux » à en profiter : c’est ce qui rend l’engagement durable.',
  ],
  [
    'article',
    "Pour désengorger les urgences, certaines provinces autorisent désormais les pharmaciens à prescrire des médicaments pour des problèmes de santé mineurs. Les médecins saluent la mesure, tout en rappelant qu'elle ne remplace pas un suivi médical régulier.",
    "Quel est l'objectif de la mesure ?",
    [
      'Réduire le nombre de pharmacies',
      'Remplacer les médecins de famille',
      'Augmenter le prix des médicaments',
      'Diminuer la pression sur les urgences',
    ],
    3,
    '« Pour désengorger les urgences » : la mesure vise à réduire leur achalandage.',
  ],
  [
    'article',
    'Le covoiturage progresse en région, où le transport collectif est rare. Des applications mettent en relation conducteurs et passagers pour les trajets quotidiens. Reste un obstacle : beaucoup hésitent encore à monter en voiture avec un inconnu.',
    "Qu'est-ce qui freine encore le covoiturage ?",
    ['Le prix de l’essence', 'La méfiance envers les inconnus', 'L’absence d’applications', 'Le manque de routes'],
    1,
    'L’obstacle cité est l’hésitation à voyager avec un inconnu.',
  ],
  [
    'opinion',
    "L'achat local a ses limites. Un produit fabriqué près de chez soi n'est pas forcément plus écologique s'il a nécessité des serres chauffées tout l'hiver. Plutôt que la distance, c'est l'ensemble du cycle de production qu'il faudrait examiner.",
    "Que conteste l'auteur ?",
    [
      'L’idée que local signifie toujours écologique',
      'L’existence des serres',
      'L’utilité de l’agriculture',
      'Le prix des produits importés',
    ],
    0,
    'Un produit local n’est « pas forcément plus écologique » : il faut regarder tout le cycle de production.',
  ],
  [
    'article',
    "Dans plusieurs écoles, des élèves du secondaire aident des aînés à utiliser tablettes et téléphones. Si les aînés gagnent en autonomie numérique, les adolescents, eux, disent avoir développé leur patience et découvert des récits de vie qu'ils ignoraient.",
    'Que retirent les adolescents de cette expérience ?',
    ['Un salaire', 'Des crédits scolaires', 'De la patience et des échanges enrichissants', 'De nouveaux appareils'],
    2,
    'Ils disent avoir développé leur patience et découvert des récits de vie.',
  ],
  [
    'article',
    "Le débat sur la densification oppose souvent, de façon caricaturale, promoteurs avides et résidents égoïstes. Cette lecture occulte l'essentiel : sans construction de logements près des services, les ménages modestes sont repoussés toujours plus loin, et les émissions liées au transport augmentent d'autant.",
    "Que reproche l'auteur au débat actuel ?",
    [
      'De trop favoriser les promoteurs',
      'D’ignorer l’avis des résidents',
      'De négliger le transport collectif',
      'De simplifier à l’excès et de masquer les vrais enjeux',
    ],
    3,
    'Le débat est « caricatural » et « occulte l’essentiel ».',
  ],
  [
    'opinion',
    "Il est tentant de voir dans chaque innovation numérique une promesse d'émancipation. Or l'histoire des techniques montre qu'un outil ne libère que ceux qui ont les moyens de se l'approprier ; pour les autres, il creuse l'écart. L'accès à l'équipement ne dit rien de la capacité à en tirer parti.",
    "Quelle idée l'auteur défend-il ?",
    [
      'Le numérique profite également à tous',
      'La technologie peut accentuer les inégalités',
      'Il faut freiner l’innovation',
      'L’équipement suffit à réduire les écarts',
    ],
    1,
    'Pour ceux qui ne peuvent se l’approprier, l’outil « creuse l’écart ».',
  ],
  [
    'article',
    "Les chercheurs ont suivi pendant dix ans des enfants ayant fréquenté un service de garde éducatif. S'ils obtiennent de meilleurs résultats en lecture à l'entrée à l'école, cet avantage s'atténue vers l'âge de neuf ans, sauf chez les enfants de milieux défavorisés, pour qui il persiste.",
    "Pour quels enfants l'effet positif dure-t-il ?",
    ['Ceux issus de milieux défavorisés', 'Tous les enfants', 'Ceux qui lisent déjà à la maison', 'Aucun enfant'],
    0,
    'L’avantage s’atténue, « sauf chez les enfants de milieux défavorisés ».',
  ],
  [
    'opinion',
    "Réclamer la gratuité des musées part d'une bonne intention, mais les données sont têtues : là où elle a été instaurée, la fréquentation a augmenté sans que le profil des visiteurs change vraiment. Le principal obstacle n'est pas le prix du billet, mais le sentiment de ne pas être à sa place.",
    "Selon l'auteur, pourquoi la gratuité ne suffit-elle pas ?",
    [
      'Elle coûte trop cher à l’État',
      'Elle fait baisser la fréquentation',
      'Le frein principal est culturel plutôt que financier',
      'Les musées manquent d’œuvres',
    ],
    2,
    'L’obstacle n’est pas le prix, mais le sentiment de ne pas être à sa place.',
  ],
  [
    'article',
    "La pénurie de main-d'œuvre a poussé plusieurs employeurs à revoir leurs exigences. Certains ont renoncé à réclamer un diplôme pour des postes où l'expérience suffit ; d'autres offrent la formation à l'interne. Les économistes y voient un rééquilibrage plutôt qu'un simple effet de conjoncture.",
    'Comment les économistes interprètent-ils ce changement ?',
    ['Comme une erreur des employeurs', 'Comme une mode passagère', 'Comme une baisse de la qualité', 'Comme une évolution durable'],
    3,
    '« Un rééquilibrage plutôt qu’un simple effet de conjoncture » : le changement est jugé durable.',
  ],
  [
    'opinion',
    "On aurait tort de réduire la francisation des nouveaux arrivants à une affaire de cours. Une langue s'apprend au travail, dans les loisirs, au fil des amitiés. Tant que les milieux de travail ne s'y engageront pas, les classes, si bonnes soient-elles, ne feront que la moitié du chemin.",
    "Que soutient l'auteur ?",
    [
      'Les cours de langue sont inutiles',
      'L’apprentissage dépend aussi de l’engagement des milieux de vie et de travail',
      'Les nouveaux arrivants refusent d’apprendre',
      'Il faut allonger la durée des cours',
    ],
    1,
    'Les cours ne font « que la moitié du chemin » sans l’engagement des milieux de travail.',
  ],
  [
    'article',
    "L'étude révèle un paradoxe : les villes qui ont le plus investi dans les pistes cyclables ne sont pas celles où la pratique du vélo a le plus progressé. La continuité du réseau compterait davantage que le nombre de kilomètres : un seul tronçon dangereux suffit à décourager les cyclistes hésitants.",
    'Quel facteur est jugé déterminant ?',
    ['La continuité et la sécurité du réseau', 'Le budget total investi', 'Le nombre de kilomètres', 'Le climat de la ville'],
    0,
    'La continuité du réseau compte davantage que le nombre de kilomètres.',
  ],
  [
    'opinion',
    "À force de vouloir tout mesurer, l'université risque de confondre ce qui compte avec ce qui se compte. Le nombre d'articles publiés ne dit rien de leur portée, et la course aux indicateurs détourne les chercheurs des projets longs et incertains, pourtant à l'origine des grandes découvertes.",
    "Quel danger l'auteur dénonce-t-il ?",
    [
      'Le manque de financement',
      'La disparition des revues savantes',
      'L’obsession des indicateurs au détriment de la recherche de fond',
      'Le trop grand nombre d’étudiants',
    ],
    2,
    'La course aux indicateurs détourne les chercheurs des projets longs et incertains.',
  ],
  [
    'article',
    "Le rapport ne conclut pas à l'échec du programme, contrairement à ce qu'ont titré plusieurs médias. Il relève que les objectifs initiaux, fixés sans données de référence, étaient invérifiables, et recommande de redéfinir les cibles avant toute nouvelle évaluation.",
    'Que constate réellement le rapport ?',
    [
      'Le programme a échoué',
      'Le programme doit être aboli',
      'Les médias ont bien résumé le rapport',
      'Les objectifs de départ ne pouvaient pas être vérifiés',
    ],
    3,
    'Les objectifs, fixés sans données de référence, étaient invérifiables.',
  ],
])
