export type TcfSpeakingTask1Prompt = {
  id: string
  taskIndex: 1
  category: string
  title: string
  intro: string
  questions: string[]
  sampleKeyPoints: string[]
  prepSeconds: number
  durationSeconds: number
}

export type TcfSpeakingTask2Prompt = {
  id: string
  taskIndex: 2
  category: string
  title: string
  scenario: string
  examinerRole: string
  examineeRole: string
  instructions: string
  suggestedQuestions: string[]
  prepSeconds: number
  durationSeconds: number
}

export type TcfSpeakingTask3Prompt = {
  id: string
  taskIndex: 3
  category: string
  title: string
  topic: string
  prompt: string
  suggestedArgumentsFor: string[]
  suggestedArgumentsAgainst: string[]
  sampleOutline: string[]
  prepSeconds: number
  durationSeconds: number
}

export type TcfSpeakingPrompt = TcfSpeakingTask1Prompt | TcfSpeakingTask2Prompt | TcfSpeakingTask3Prompt

export const TCF_SPEAKING_TASK1_PROMPTS: TcfSpeakingTask1Prompt[] = [
  {
    id: 'eo-t1-01',
    category: 'Vie quotidienne',
    title: 'Présentation personnelle et routine',
    intro: "L'examinateur vous demande de vous présenter et de décrire une journée type dans votre vie.",
    questions: [
      'Bonjour, pouvez-vous vous présenter brièvement (nom, prénom, nationalité, profession) ?',
      'À quoi ressemble généralement une journée ordinaire pour vous, du matin au soir ?',
      'Quel est le moment de la journée que vous préférez et pour quelle raison ?',
    ],
    sampleKeyPoints: [
      'Présentation générale claire (situation familiale, parcours professionnel)',
      'Description chronologique des activités quotidiennes (lever, transport, travail, repas)',
      'Expression des préférences personnelles avec justification nuancée',
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-02',
    category: 'Environnement',
    title: "Votre ville d'origine ou votre quartier",
    intro: "L'examinateur vous interroge sur votre cadre de vie actuel ou votre ville d'origine.",
    questions: [
      'Où avez-vous grandi et comment décririez-vous cet endroit ?',
      "Qu'est-ce qui vous plaît le plus dans votre quartier d'habitation actuel ?",
      'Si vous pouviez changer une chose dans votre environnement urbain, que choisiriez-vous ?',
    ],
    sampleKeyPoints: [
      'Description vivante des caractéristiques géographiques et culturelles de la ville',
      'Évocation des commerces, parcs, transports et ambiance du quartier',
      "Proposition d'amélioration argumentée (espaces verts, pistes cyclables, propreté)",
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-03',
    category: 'Loisirs',
    title: 'Loisirs et activités de fin de semaine',
    intro: "L'examinateur cherche à connaître la façon dont vous occupez votre temps libre.",
    questions: [
      'Quelles sont vos activités préférées pendant vos temps de repos ?',
      "Préférez-vous passer vos week-ends chez vous ou à l'extérieur ?",
      'Avez-vous une passion ou un passe-temps que vous pratiquez depuis longtemps ?',
    ],
    sampleKeyPoints: [
      'Variété des activités de loisirs (lecture, sport, cuisine, cinéma, bricolage)',
      'Comparaison entre activités solitaires et sorties entre amis ou en famille',
      "Récit d'une passion personnelle et de son évolution dans le temps",
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-04',
    category: 'Parcours',
    title: 'Parcours professionnel et études',
    intro: "L'examinateur vous demande de retracer vos études et vos expériences de travail.",
    questions: [
      "Quelle formation ou quelles études avez-vous suivies à l'université ou au collège ?",
      'En quoi consiste votre métier au quotidien ?',
      "Qu'est-ce qui vous apporte le plus de satisfaction dans votre travail ?",
    ],
    sampleKeyPoints: [
      "Vocabulaire lié aux diplômes, compétences et secteurs d'activité",
      "Explication claire des responsabilités professionnelles et du travail d'équipe",
      'Motivation personnelle et accomplissements dont on est fier',
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-05',
    category: "Projet d'immigration",
    title: 'Apprentissage du français et projet canadien',
    intro: "L'examinateur s'intéresse à votre motivation linguistique et à votre projet de vie.",
    questions: [
      'Depuis combien de temps apprenez-vous la langue française ?',
      'Quelles sont les principales difficultés que vous avez rencontrées et comment les surmontez-vous ?',
      "Pourquoi avez-vous choisi le Canada comme destination d'immigration ou d'études ?",
    ],
    sampleKeyPoints: [
      "Chronologie de l'apprentissage (cours, immersion, pratique autonome)",
      'Obstacles linguistiques (compréhension orale, prononciation, grammaire) et solutions',
      'Attraits du Canada (qualité de vie, sécurité, opportunités professionnelles, nature)',
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-06',
    category: 'Gastronomie',
    title: 'Habitudes alimentaires et cuisine préférée',
    intro: "L'examinateur aborde le thème de l'alimentation et des traditions culinaires.",
    questions: [
      'Aimez-vous cuisiner ou préférez-vous manger au restaurant ?',
      'Quel est le plat traditionnel de votre pays que vous recommanderiez à un ami ?',
      'Avez-vous déjà goûté des spécialités culinaires canadiennes ou québécoises ?',
    ],
    sampleKeyPoints: [
      "Description d'une recette ou d'un plat typique (ingrédients, saveurs, préparation)",
      'Habitudes de repas en famille ou entre amis',
      "Curiosité pour la poutine, le sirop d'érable ou les mets locaux",
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-07',
    category: 'Voyages',
    title: 'Un voyage marquant dans votre vie',
    intro: "L'examinateur vous invite à raconter une expérience de voyage particulièrement mémorable.",
    questions: [
      "Quel est le pays ou la région qui vous a le plus impressionné lors d'un voyage ?",
      'Racontez une anecdote ou un souvenir marquant lié à ce séjour.',
      'Quel genre de voyageur êtes-vous : plutôt aventurier sac au dos ou adepte du confort ?',
    ],
    sampleKeyPoints: [
      "Récit d'un voyage marquant au passé (passé composé et imparfait maîtrisés)",
      "Description des paysages, des rencontres culturelles et de l'accueil des habitants",
      'Définition de son style de voyage personnel et vision du dépaysement',
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-08',
    category: 'Santé et sport',
    title: 'Pratique sportive et bien-être physique',
    intro: "L'examinateur vous questionne sur vos habitudes sportives et votre hygiène de vie.",
    questions: [
      'Pratiquez-vous une activité sportive régulière ? Si oui, laquelle et à quel rythme ?',
      "Selon vous, quelle est l'importance du sport pour préserver la santé mentale ?",
      'Y a-t-il une nouvelle discipline sportive que vous aimeriez essayer prochainement ?',
    ],
    sampleKeyPoints: [
      "Description de la routine d'entraînement (course, natation, salle de sport, marche)",
      'Réflexion sur les bienfaits psychologiques (lutte contre le stress, énergie)',
      "Intérêt pour les sports d'hiver canadiens (patin à glace, raquette, ski)",
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-09',
    category: 'Culture',
    title: 'Goûts culturels, musique et cinéma',
    intro: "L'examinateur vous interroge sur vos préférences artistiques et vos sorties culturelles.",
    questions: [
      "Quel genre de musique ou d'artistes écoutez-vous le plus souvent au quotidien ?",
      'Préférez-vous regarder des films à la maison ou aller au cinéma en salle ?',
      "Parlez-moi d'une œuvre culturelle (chanson, film, exposition) qui vous a récemment ému.",
    ],
    sampleKeyPoints: [
      'Vocabulaire lié aux genres artistiques et musicaux',
      'Comparaison entre expérience collective au cinéma et streaming à domicile',
      'Évocation des émotions ressenties face à une création artistique',
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-10',
    category: 'Inspiration',
    title: 'Une personne qui vous inspire au quotidien',
    intro: "L'examinateur vous demande de décrire une personnalité ou un proche qui représente un modèle pour vous.",
    questions: [
      'Quelle personne admirez-vous le plus dans votre entourage ou parmi les figures publiques ?',
      'Quelles sont les qualités morales ou professionnelles qui font sa force ?',
      'De quelle manière son exemple influence-t-il vos propres choix de vie ?',
    ],
    sampleKeyPoints: [
      "Portrait élogieux d'un parent, mentor ou personnalité historique",
      'Qualités humaines mises en avant (persévérance, générosité, courage, empathie)',
      'Impact concret sur ses propres valeurs morales et décisions quotidiennes',
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-11',
    category: 'Nature',
    title: "Votre saison préférée de l'année",
    intro: "L'examinateur aborde le climat, les saisons et votre rapport aux changements de température.",
    questions: [
      "Quelle est votre saison favorite entre l'été, l'automne, l'hiver et le printemps ?",
      'Quelles sont les activités que vous aimez particulièrement pratiquer durant cette saison ?',
      'Comment vous adaptez-vous aux climats froids ou rigoureux ?',
    ],
    sampleKeyPoints: [
      "Description sensorielle des paysages saisonniers (couleurs d'automne, neige d'hiver, chaleur d'été)",
      "Activités associées à chaque période de l'année",
      "Attitude positive et équipement adéquat face aux rigueurs de l'hiver",
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-12',
    category: 'Langues',
    title: 'Le multilinguisme et les langues vivantes',
    intro: "L'examinateur vous interroge sur votre rapport aux langues et votre expérience multilingue.",
    questions: [
      'Combien de langues maîtrisez-vous et dans quel contexte les avez-vous apprises ?',
      "Pensez-vous qu'apprendre une langue modifie notre façon de penser le monde ?",
      'Si vous pouviez maîtriser instantanément une nouvelle langue demain, laquelle choisiriez-vous ?',
    ],
    sampleKeyPoints: [
      'Présentation de sa langue maternelle et des langues secondes acquises',
      'Lien entre vocabulaire, culture et vision du monde',
      "Désir de découverte linguistique et ouverture d'esprit",
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-13',
    category: 'Souvenirs',
    title: "Souvenirs d'enfance et jeunesse",
    intro: "L'examinateur vous invite à partager un souvenir marquant de vos premières années.",
    questions: [
      "Quel est l'un de vos souvenirs d'enfance les plus précieux ?",
      'Quels jeux ou activités occupaient la majeure partie de vos journées à cette époque ?',
      "En quoi le monde des enfants d'aujourd'hui est-il différent de celui de votre enfance ?",
    ],
    sampleKeyPoints: [
      "Usage naturel de l'imparfait pour décrire des habitudes passées",
      "Évocation des jeux de plein air, des amis d'enfance et des réunions familiales",
      "Comparaison générationnelle avec l'omniprésence actuelle des écrans",
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-14',
    category: 'Avenir',
    title: "Vos projets d'avenir à moyen terme",
    intro: "L'examinateur s'intéresse à vos objectifs personnels et professionnels pour les années à venir.",
    questions: [
      "Où vous imaginez-vous vivre et travailler d'ici trois à cinq ans ?",
      'Quel est le plus grand défi que vous souhaitez relever dans un avenir proche ?',
      "Comment comptez-vous vous intégrer dans votre nouvelle communauté d'accueil ?",
    ],
    sampleKeyPoints: [
      'Emploi maîtrisé du futur simple et du conditionnel pour exprimer des projets',
      'Équilibre entre ambitions professionnelles et épanouissement personnel',
      "Volonté d'intégration civique et de participation communautaire",
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-15',
    category: 'Technologie',
    title: 'Place des technologies dans votre quotidien',
    intro: "L'examinateur examine votre usage des écrans, des applications et des réseaux sociaux.",
    questions: [
      'Combien de temps passez-vous sur votre téléphone intelligent chaque jour ?',
      'Les technologies facilitent-elles votre vie ou créent-elles plutôt du stress ?',
      "Pourriez-vous vous passer d'Internet pendant toute une semaine sans angoisse ?",
    ],
    sampleKeyPoints: [
      "Analyse lucide de son temps d'écran et des outils numériques utilisés",
      "Avantages de la communication instantanée vs dispersion de l'attention",
      'Expérience de déconnexion volontaire ou gestion équilibrée du numérique',
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-16',
    category: 'Mobilité',
    title: 'Vos déplacements et moyens de transport',
    intro: "L'examinateur aborde la question de vos trajets quotidiens et de vos préférences de transport.",
    questions: [
      'Quel moyen de transport utilisez-vous principalement pour aller travailler ou étudier ?',
      'Quels sont les avantages et inconvénients de ce mode de déplacement ?',
      'Seriez-vous prêt à renoncer à la voiture individuelle si les transports collectifs étaient parfaits ?',
    ],
    sampleKeyPoints: [
      'Description du trajet quotidien (durée, correspondances, régularité)',
      'Poids écologique et financier du transport dans son budget',
      'Avis argumenté sur la cohabitation entre marche, vélo, bus et automobile',
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-17',
    category: 'Animaux',
    title: 'Votre rapport aux animaux de compagnie',
    intro: "L'examinateur s'intéresse à votre relation avec les animaux domestiques.",
    questions: [
      'Avez-vous ou avez-vous déjà eu un animal de compagnie chez vous ?',
      "Selon vous, qu'apporte la présence d'un animal dans une famille avec des enfants ?",
      "Que pensez-vous des responsabilités qu'implique l'adoption d'un animal ?",
    ],
    sampleKeyPoints: [
      "Récit d'une expérience passée ou présente avec un chien, un chat ou un autre compagnon",
      "Rôle éducatif et affectif de l'animal auprès des enfants et des personnes seules",
      'Prise de conscience des engagements matériels, financiers et moraux sur le long terme',
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-18',
    category: 'Traditions',
    title: 'Fêtes et célébrations familiales',
    intro: "L'examinateur vous interroge sur les célébrations culturelles qui vous tiennent à cœur.",
    questions: [
      'Quelle est la fête la plus importante célébrée dans votre culture ou votre famille ?',
      'Comment se déroulent les préparatifs et quelles sont les coutumes associées ?',
      'Quel rôle jouent ces fêtes traditionnelles pour maintenir les liens entre proches ?',
    ],
    sampleKeyPoints: [
      "Présentation d'une fête traditionnelle (Nouvel An, fêtes de fin d'année, fêtes culturelles)",
      'Rituels associés (cadeaux, costumes, danses, réunions de famille, mets festifs)',
      'Importance de la transmission culturelle et de la mémoire collective',
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-19',
    category: 'Lectures et films',
    title: 'Une œuvre qui a influencé votre pensée',
    intro: "L'examinateur vous invite à présenter un livre ou un film qui a laissé une trace indélébile.",
    questions: [
      'Aimez-vous lire des livres régulièrement ? Quel est le dernier livre que vous avez lu ?',
      'Y a-t-il un film ou un roman qui a profondément changé votre regard sur un sujet ?',
      'Pourquoi recommanderiez-vous cette œuvre à un ami sans hésiter ?',
    ],
    sampleKeyPoints: [
      "Résumé concis de l'intrigue ou du thème central de l'œuvre",
      'Analyse des personnages et du message philosophique ou social véhiculé',
      'Arguments persuasifs pour inciter son interlocuteur à découvrir cette œuvre',
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
  {
    id: 'eo-t1-20',
    category: 'Détente',
    title: 'Votre havre de paix pour décompresser',
    intro: "L'examinateur cherche à savoir où et comment vous rechargez vos batteries.",
    questions: [
      'Où allez-vous lorsque vous ressentez le besoin impérieux de vous isoler et de vous détendre ?',
      'Quelles sont les sensations ou les activités qui vous apaisent le plus rapidement ?',
      'Arrivez-vous facilement à couper avec le stress du travail en fin de journée ?',
    ],
    sampleKeyPoints: [
      "Description détaillée d'un lieu ressourçant (parc, bord de l'eau, bibliothèque, forêt, balcon)",
      'Techniques de relaxation (marche méditative, respiration, musique douce, lecture)',
      "Importance de l'hygiène de vie pour préserver son équilibre nerveux",
    ],
    prepSeconds: 0,
    durationSeconds: 120,
    taskIndex: 1,
  },
]

export const TCF_SPEAKING_TASK2_PROMPTS: TcfSpeakingTask2Prompt[] = [
  {
    id: 'eo-t2-01',
    category: 'Logement',
    title: 'Renseignements pour louer un appartement',
    scenario:
      "Vous avez vu une annonce pour un appartement de trois pièces à louer. Vous téléphonez au propriétaire (joué par l'examinateur) pour obtenir tous les renseignements nécessaires avant de visiter.",
    examinerRole: "Le propriétaire de l'appartement à louer.",
    examineeRole: "Le locataire potentiel intéressé par l'annonce.",
    instructions:
      'Posez une dizaine de questions précises pour obtenir des informations complètes sur le logement (loyer, charges, électroménagers inclus, transports, animaux, date de disponibilité).',
    suggestedQuestions: [
      "Bonjour, je vous appelle au sujet de l'appartement à louer. Est-il toujours disponible ?",
      'Quel est le montant exact du loyer mensuel et les charges sont-elles comprises ?',
      "Le chauffage et l'eau chaude sont-ils inclus dans le prix annoncé ?",
      'Est-ce que les électroménagers comme le réfrigérateur et la cuisinière sont fournis ?',
      "À quel étage se situe l'appartement et l'immeuble dispose-t-il d'un ascenseur ?",
      'Y a-t-il une place de stationnement réservée pour les résidents ?',
      'Les animaux de compagnie sont-ils acceptés dans le bail ?',
      "À quelle distance se trouvent les stations de métro ou les arrêts d'autobus les plus proches ?",
      "Quelle est la date exacte de disponibilité pour l'emménagement ?",
      "Serait-il possible de convenir d'une visite cette fin de semaine ?",
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-02',
    category: 'Éducation',
    title: 'Inscription à une école de langues',
    scenario:
      "Vous souhaitez perfectionner votre français pour vos démarches professionnelles. Vous vous rendez au secrétariat d'un centre de langues pour poser des questions au responsable.",
    examinerRole: "Le responsable pédagogique de l'école de langues.",
    examineeRole: "Un nouvel apprenant souhaitant s'inscrire.",
    instructions:
      "Posez des questions sur les formules de cours (intensifs, du soir), les tarifs, les dates de session, les méthodes pédagogiques et les tests d'évaluation.",
    suggestedQuestions: [
      'Bonjour, quelles sont les différentes formules de cours de français que vous proposez ?',
      'Proposez-vous des cours du soir adaptés aux personnes qui travaillent à temps plein ?',
      "Combien d'heures de cours par semaine compte le programme intermédiaire ?",
      "Combien d'étudiants y a-t-il en moyenne par groupe ?",
      'Les professeurs sont-ils tous locuteurs natifs et certifiés en enseignement ?',
      "Faut-il passer un test de niveau préalable avant de procéder à l'inscription ?",
      'Quel est le coût total pour une session trimestrielle de cours ?',
      "Le matériel pédagogique et les manuels sont-ils compris dans les frais d'inscription ?",
      'Délivrez-vous une attestation officielle ou un certificat à la fin de la formation ?',
      'Quelles sont les modalités de paiement et proposez-vous des facilités en plusieurs versements ?',
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-03',
    category: 'Animaux',
    title: 'Adoption responsable dans un refuge animalier',
    scenario:
      "Vous souhaitez adopter un chien ou un chat dans un refuge. Vous interrogez l'employé du refuge sur la démarche d'adoption, les soins et l'histoire des animaux.",
    examinerRole: "L'agent d'accueil du refuge pour animaux.",
    examineeRole: "Un particulier désireux d'adopter un animal de compagnie.",
    instructions:
      "Interrogez l'examinateur sur les démarches administratives, le passé de l'animal, son état de santé, ses ententes et les frais requis.",
    suggestedQuestions: [
      "Bonjour, j'aimerais savoir quelle est la procédure complète pour adopter un animal chez vous ?",
      "Quels critères devez-vous vérifier auprès des futurs adoptants avant d'accorder l'adoption ?",
      "Connaissez-vous le passé et l'histoire des animaux qui se trouvent actuellement au refuge ?",
      'Les animaux sont-ils tous vaccinés, vermifugés et micropucés avant leur départ ?',
      "La stérilisation est-elle systématiquement comprise dans les frais d'adoption ?",
      "Comment évaluez-vous le comportement de l'animal avec les jeunes enfants et les autres animaux ?",
      "Offrez-vous une période d'essai ou d'adaptation pour s'assurer que tout se passe bien à la maison ?",
      "Fournissez-vous des conseils ou un suivi avec un éducateur canin après l'adoption ?",
      "À combien s'élèvent les frais de contribution pour l'adoption d'un chien adulte ?",
      "Puis-je passer du temps dans une pièce réservée avec l'animal aujourd'hui pour faire connaissance ?",
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-04',
    category: 'Sport',
    title: 'Abonnement dans une salle de sport',
    scenario:
      "Vous voulez vous remettre en forme et vous vous renseignez à l'accueil d'un centre de conditionnement physique municipal ou privé.",
    examinerRole: 'Le conseiller de la salle de sport.',
    examineeRole: 'Un client potentiel intéressé par un abonnement annuel.',
    instructions:
      "Renseignez-vous sur les équipements, les cours collectifs, les horaires d'ouverture, les entraîneurs personnels et les clauses de résiliation.",
    suggestedQuestions: [
      "Bonjour, quelles sont les formules d'abonnement disponibles dans votre centre de conditionnement physique ?",
      "Quels sont vos horaires d'ouverture pendant la semaine et les fins de semaine ?",
      "Les cours collectifs de yoga, spinning et pilates sont-ils inclus dans l'abonnement standard ?",
      "Faut-il réserver sa place à l'avance pour participer aux cours de groupe populaires ?",
      "Proposez-vous un bilan de santé ou une séance d'évaluation initiale avec un entraîneur certifié ?",
      "La salle dispose-t-elle d'un espace d'entraînement fonctionnel et d'une piscine ou d'un sauna ?",
      'Y a-t-il des casiers sécurisés et des douches gratuites à la disposition des adhérents ?',
      'Existe-t-il des tarifs préférentiels pour les étudiants, les couples ou les entreprises ?',
      'Est-il possible de suspendre temporairement son abonnement en cas de blessure ou de vacances ?',
      "Puis-je bénéficier d'une séance d'essai gratuite avant de m'engager sur un contrat annuel ?",
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-05',
    category: 'Automobile',
    title: "Achat d'une voiture d'occasion à un particulier",
    scenario:
      "Vous avez repéré une annonce pour une voiture d'occasion vendue par un particulier. Vous téléphonez au vendeur pour poser des questions techniques.",
    examinerRole: "Le propriétaire vendeur de la voiture d'occasion.",
    examineeRole: "L'acheteur potentiel qui se renseigne.",
    instructions:
      "Posez des questions sur le kilométrage, l'état général, les entretiens effectués, la consommation, les pneus et convenez d'un essai routier.",
    suggestedQuestions: [
      'Bonjour, je vous appelle concernant votre annonce pour la voiture. Quel est son kilométrage exact ?',
      "Depuis combien d'années possédez-vous ce véhicule et quel usage en faisiez-vous ?",
      "Avez-vous en votre possession le carnet d'entretien complet avec toutes les factures de révision ?",
      'La courroie de distribution et les freins ont-ils été changés récemment ?',
      'La voiture a-t-elle déjà été impliquée dans un accident de la route ou subi des réparations majeures ?',
      'Y a-t-il des traces de rouille sur la carrosserie ou des dysfonctionnements électriques ?',
      "Le véhicule est-il vendu avec un ensemble de pneus d'hiver montés sur jantes ?",
      'Quelle est sa consommation moyenne de carburant en ville et sur autoroute ?',
      'Le contrôle technique de sécurité provincial a-t-il été passé avec succès ?',
      "Seriez-vous ouvert à ce que j'amène le véhicule chez mon garagiste pour une inspection avant l'achat ?",
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-06',
    category: 'Tourisme',
    title: "Réservation d'un gîte en forêt pour un week-end",
    scenario:
      "Vous planifiez une fin de semaine en pleine nature avec des amis. Vous appelez le propriétaire d'une auberge de campagne pour obtenir les détails.",
    examinerRole: 'Le propriétaire du gîte touristique en région.',
    examineeRole: 'Le voyageur qui organise le séjour pour un groupe de quatre personnes.',
    instructions:
      "Interrogez l'examinateur sur les commodités, la restauration, les sentiers à proximité, le tarif global et les conditions d'annulation.",
    suggestedQuestions: [
      'Bonjour, je cherche à réserver pour quatre personnes le week-end du 15 octobre. Avez-vous de la disponibilité ?',
      'Combien de chambres indépendantes compte votre gîte et comment sont configurés les lits ?',
      'Le petit-déjeuner du terroir est-il inclus dans le prix de la nuitée ?',
      "Proposez-vous une table d'hôte pour le souper ou y a-t-il une cuisine tout équipée accessible ?",
      "Quels types d'activités de plein air peut-on pratiquer directement depuis votre établissement ?",
      'Prêtez-vous du matériel comme des canots, des gilets de sauvetage ou des vélos de montagne ?',
      'Y a-t-il un accès au réseau Internet sans fil dans les chambres ou est-ce un lieu totalement déconnecté ?',
      'Les chiens sont-ils admis dans votre gîte et y a-t-il un supplément tarifaire ?',
      'Quel est le montant total du séjour, taxes comprises, pour deux nuits ?',
      "Quelles sont vos conditions d'annulation en cas d'imprévu météorologique de dernière minute ?",
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-07',
    category: 'Bénévolat',
    title: 'Engagement dans une association caritative',
    scenario:
      'Vous souhaitez donner de votre temps libre à un organisme communautaire qui aide les personnes sans-abri. Vous rencontrez le coordinateur des bénévoles.',
    examinerRole: "Le coordinateur des bénévoles de l'organisme caritatif.",
    examineeRole: "Un citoyen souhaitant s'engager bénévolement.",
    instructions:
      "Posez des questions sur les besoins de l'organisme, les missions possibles, la fréquence exigée, la formation offerte et l'encadrement des équipes.",
    suggestedQuestions: [
      'Bonjour, quelles sont les missions principales pour lesquelles vous recherchez des bénévoles actuellement ?',
      'Faut-il posséder des compétences spécifiques en travail social pour pouvoir vous aider ?',
      "Combien d'heures par semaine ou par mois demandez-vous au minimum pour s'engager ?",
      'Est-il possible de participer uniquement les samedis ou en soirée après le travail ?',
      "Proposez-vous une formation d'accueil pour préparer les nouveaux bénévoles au contact avec le public ?",
      'Comment sont organisées les équipes sur le terrain lors des distributions de repas chauds ?',
      'Y a-t-il un encadrement assuré par des intervenants professionnels en cas de situation délicate ?',
      'Pouvons-nous également aider sur des tâches administratives, de communication ou de levée de fonds ?',
      "Quelles sont les démarches administratives et les vérifications d'antécédents requises pour commencer ?",
      "Quand a lieu la prochaine réunion d'information pour rencontrer les autres membres ?",
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-08',
    category: 'Famille',
    title: "Inscription d'un enfant à un camp de jour",
    scenario:
      'Vous voulez inscrire votre enfant de sept ans à un camp de vacances municipal cet été. Vous interrogez le directeur du programme jeunesse.',
    examinerRole: 'Le directeur du camp de jour municipal.',
    examineeRole: "Un parent d'élève cherchant des informations pour son enfant.",
    instructions:
      "Renseignez-vous sur la tranche d'âge, les activités artistiques et sportives, la sécurité, les repas et les horaires du service de garde.",
    suggestedQuestions: [
      "Bonjour, quelle est la tranche d'âge exacte des enfants accueillis dans votre camp de jour ?",
      "Quel est le programme type d'une journée entre les activités sportives, artistiques et scientifiques ?",
      "Quel est le ratio d'animateurs par enfant pour garantir une surveillance et une sécurité maximales ?",
      'Les moniteurs ont-ils tous suivi une formation certifiée en premiers soins et réanimation ?',
      'Proposez-vous des sorties extérieures comme des visites de musées, des fermes ou des baignades à la plage ?',
      'Les repas chauds et les collations saines sont-ils fournis ou les parents doivent-ils préparer une boîte à lunch ?',
      'Comment gérez-vous les allergies alimentaires graves et les protocoles médicaux des enfants ?',
      "Quels sont les horaires d'ouverture du service de garde le matin avant le camp et le soir après les activités ?",
      "Existe-t-il un tarif préférentiel pour les résidents de la municipalité ou pour l'inscription d'une fratrie ?",
      "Quelle est la date limite pour déposer le dossier d'inscription officiel ?",
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-09',
    category: 'Gastronomie',
    title: 'Atelier de pâtisserie française pour amateurs',
    scenario:
      "Vous souhaitez apprendre à faire des croissants et des macarons traditionnels. Vous téléphonez à l'école de cuisine qui dispense ces cours.",
    examinerRole: "Le chef pâtissier formateur de l'école.",
    examineeRole: 'Un passionné de cuisine souhaitant suivre un atelier.',
    instructions:
      "Posez des questions sur le déroulement du cours, les ingrédients, le niveau requis, ce que l'on rapporte chez soi et le tarif.",
    suggestedQuestions: [
      "Bonjour, vos ateliers de pâtisserie sont-ils accessibles aux personnes qui n'ont aucune expérience en boulangerie ?",
      "Combien de temps dure l'atelier consacré aux viennoiseries et aux macarons ?",
      'Combien de participants y a-t-il par poste de travail pendant la session ?',
      'Tout le matériel de cuisine, tabliers et ingrédients de première qualité sont-ils fournis sur place ?',
      "Est-ce que chaque participant manipule la pâte individuellement ou s'agit-il d'un travail collectif ?",
      'Repart-on chez soi avec les créations culinaires préparées pendant le cours ?',
      'Remettez-vous un livret contenant les fiches recettes détaillées et les astuces du chef ?',
      'Que se passe-t-il si un participant a une intolérance au gluten ou aux produits laitiers ?',
      "Quel est le coût d'une demi-journée de formation par personne ?",
      'Proposez-vous des cartes-cadeaux valables pour réserver un créneau ultérieurement ?',
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-10',
    category: 'Culture',
    title: 'Visite guidée historique privée',
    scenario:
      "Vous recevez de la famille de l'étranger et vous voulez organiser une visite guidée privée du Vieux-Montréal ou du Vieux-Québec avec un guide agréé.",
    examinerRole: 'Le guide touristique professionnel indépendant.',
    examineeRole: 'Le client qui planifie la visite culturelle.',
    instructions:
      "Interrogez l'examinateur sur les itinéraires proposés, la durée de la visite, les langues parlées, l'accessibilité pour les aînés et le tarif forfaitaire.",
    suggestedQuestions: [
      'Bonjour, proposez-vous des visites historiques guidées privées pour des petits groupes familiaux de cinq personnes ?',
      'Quels sont les principaux monuments et lieux historiques traversés lors de votre circuit classique ?',
      'Combien de kilomètres à pied représente le parcours et la marche est-elle accessible à une personne âgée ?',
      'Quelle est la durée moyenne de la visite et prévoyez-vous des pauses dans des cafés patrimoniaux ?',
      'La visite peut-elle être dispensée en français tout en traduisant les passages clés en espagnol pour mes proches ?',
      "Est-il possible de personnaliser le parcours selon nos centres d'intérêt spécifiques, comme l'architecture coloniale ?",
      'Que se passe-t-il en cas de forte pluie le jour prévu : maintenez-vous la visite ou reportez-vous ?',
      'Le tarif est-il calculé par personne ou appliquez-vous un forfait global pour le groupe entier ?',
      'Où se situe exactement le point de départ de la visite dans le quartier historique ?',
      "Combien de temps à l'avance faut-il réserver pour s'assurer de votre disponibilité un samedi après-midi ?",
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-11',
    category: 'Artisanat',
    title: 'Atelier de menuiserie communautaire',
    scenario:
      "Vous voulez apprendre à travailler le bois pour fabriquer une petite étagère. Vous vous renseignez auprès d'un atelier d'artisans partagé.",
    examinerRole: "Le responsable de l'atelier communautaire de menuiserie.",
    examineeRole: 'Un bricoleur débutant qui cherche un espace de travail encadré.',
    instructions:
      "Renseignez-vous sur les cours d'initiation à la sécurité, l'accès aux machines-outils, le stockage du bois et les tarifs d'adhésion.",
    suggestedQuestions: [
      "Bonjour, quelles sont les étapes obligatoires pour qu'un débutant puisse utiliser vos machines à bois ?",
      'Proposez-vous une formation de sécurité pour apprendre à manipuler scies circulaires et raboteuses sans danger ?',
      'Faut-il apporter son propre bois ou vendez-vous des essences locales directement sur place ?',
      "Y a-t-il des animateurs ou menuisiers d'expérience présents en permanence pour conseiller les adhérents ?",
      'Les équipements de protection individuelle comme les lunettes et casques antibruit sont-ils fournis ?',
      "Peut-on stocker un meuble en cours de fabrication dans vos locaux d'une semaine sur l'autre ?",
      "Quelles sont les formules de tarification : à l'heure, à la journée ou sous forme d'abonnement mensuel ?",
      "Quels sont vos jours et plages horaires d'ouverture au public ?",
      "L'atelier organise-t-il des projets collectifs pour fabriquer du mobilier urbain ou associatif ?",
      "Puis-je venir visiter l'atelier demain pour voir les installations avant d'adhérer ?",
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-12',
    category: 'Plein air',
    title: 'Randonnée alpine guidée en parc national',
    scenario:
      'Vous préparez une randonnée de haute montagne sur deux jours. Vous téléphonez au bureau des guides pour évaluer la faisabilité.',
    examinerRole: 'Le guide de haute montagne du parc national.',
    examineeRole: 'Le randonneur intermédiaire qui demande des détails techniques.',
    instructions:
      "Posez des questions sur le dénivelé, l'équipement obligatoire, le refuge d'altitude, la nourriture et les compétences physiques indispensables.",
    suggestedQuestions: [
      "Bonjour, quel est le niveau de forme physique et d'expérience alpine exigé pour ce trek de deux jours ?",
      "Quel est le dénivelé positif total et le nombre d'heures de marche prévus par jour ?",
      'Où passe-t-on la nuit : dans un refuge gardé avec dortoirs ou sous la tente en bivouac ?',
      'Les repas chauds du soir et les déjeuners sont-ils inclus dans la prestation du guide ?',
      'Quel type de sac à dos et de chaussures de marche rigides recommandez-vous pour ce type de terrain rocheux ?',
      "Faut-il emporter un système de purification de l'eau ou y a-t-il des sources potables sur le tracé ?",
      'Quelle est la taille maximale du groupe encadré par un seul guide pour garantir la sécurité ?',
      "Comment gérez-vous les changements météorologiques brusques ou les risques d'orage en altitude ?",
      "À combien s'élève le prix par personne incluant l'encadrement et les nuitées en refuge ?",
      "Quelle est la politique de remboursement si l'excursion doit être annulée pour des raisons de sécurité majeure ?",
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-13',
    category: 'Vacances',
    title: "Location d'un chalet au bord de l'eau",
    scenario:
      "Vous souhaitez louer un chalet rustique au bord d'un lac pour une semaine de vacances en famille. Vous contactez le gestionnaire immobilier.",
    examinerRole: 'Le gestionnaire de chalets locatifs en villégiature.',
    examineeRole: 'Le locataire en quête de tranquillité pour sa famille.',
    instructions:
      "Interrogez l'examinateur sur les équipements du chalet (cuisine, lave-linge, canot), la propreté du lac pour la baignade, le wifi et l'épicerie la plus proche.",
    suggestedQuestions: [
      "Bonjour, le chalet au bord du lac est-il encore disponible pour la première semaine d'août ?",
      "Quelle est la capacité maximale d'accueil en nombre d'adultes et d'enfants ?",
      "L'accès au lac est-il direct et la rive est-elle sécuritaire pour la baignade de jeunes enfants ?",
      'Fournissez-vous des embarcations nautiques comme un pédalo, un kayak ou une barque à rames ?',
      "Le chalet dispose-t-il d'un lave-linge, d'un lave-vaisselle et d'une literie complète ?",
      'Y a-t-il un foyer intérieur au bois et le bois de chauffage est-il fourni pour la semaine ?',
      'Le réseau cellulaire et la connexion Internet haut débit sont-ils fiables en cas de travail ponctuel ?',
      "À quelle distance en voiture se trouvent l'épicerie et la pharmacie les plus proches du chalet ?",
      "Quel est le montant de l'acompte demandé à la réservation et à combien s'élève le dépôt de garantie ?",
      "À quelle heure précise s'effectuent l'arrivée le samedi et le départ en fin de séjour ?",
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-14',
    category: 'Services municipaux',
    title: 'Services et adhésion à la bibliothèque municipale',
    scenario: "Vous venez d'emménager dans un nouveau quartier et vous vous présentez au comptoir de prêt de la bibliothèque publique.",
    examinerRole: "Le bibliothécaire responsable de l'accueil.",
    examineeRole: 'Le nouvel usager curieux des services offerts.',
    instructions:
      "Renseignez-vous sur les pièces d'identité nécessaires pour la carte, le nombre de livres empruntables, les ressources numériques et les activités pour enfants.",
    suggestedQuestions: [
      "Bonjour, quelles pièces justificatives dois-je fournir pour créer une carte d'usager gratuite ?",
      'Combien de documents (livres, revues, disques, films) peut-on emprunter simultanément avec une seule carte ?',
      'Quelle est la durée maximale du prêt et peut-on renouveler les emprunts en ligne depuis chez soi ?',
      'La bibliothèque donne-t-elle accès à des plateformes numériques de livres électroniques, de presse et de musique ?',
      'Avez-vous des espaces silencieux équipés de prises électriques et du wifi pour étudier sur place ?',
      'Y a-t-il des ordinateurs en libre accès et des imprimantes pour les usagers ?',
      'Organisez-vous des clubs de lecture pour adultes ou des heures du conte hebdomadaires pour les enfants ?',
      "Proposez-vous des cours d'informatique de base ou des ateliers d'apprentissage du français pour les nouveaux arrivants ?",
      "Quels sont vos horaires d'ouverture pendant la semaine et durant la période estivale ?",
      'Peut-on faire venir un document conservé dans une autre succursale du réseau municipal gratuitement ?',
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-15',
    category: 'Vie de quartier',
    title: 'Organisation de la fête des voisins de rue',
    scenario:
      'Vous voulez organiser un grand banquet convivial dans votre ruelle pour faire connaissance avec les résidents. Vous rencontrez le responsable du comité de quartier.',
    examinerRole: "L'agent municipal chargé du développement communautaire.",
    examineeRole: "Le citoyen bénévole qui prend l'initiative de la fête de quartier.",
    instructions:
      "Interrogez l'examinateur sur les permis municipaux, la fermeture temporaire de la rue, le prêt de matériel (tables, tentes) et les subventions possibles.",
    suggestedQuestions: [
      "Bonjour, quelles sont les démarches officielles pour obtenir l'autorisation de fermer une ruelle pour une journée ?",
      "Combien de temps avant la date prévue de l'événement faut-il déposer la demande de permis municipal ?",
      "Faut-il recueillir les signatures d'accord de la majorité des résidents riverains pour valider le projet ?",
      'La municipalité peut-elle prêter du matériel logistique comme des barrières, des tables pliantes ou des poubelles de recyclage ?',
      "Existe-t-il un petit budget ou une subvention locale pour financer l'achat de boissons, de charbon ou d'animations pour enfants ?",
      "Quelles sont les règles strictes en matière de volume sonore et d'heure limite pour arrêter la musique le soir ?",
      "A-t-on le droit d'installer un barbecue commun ou faut-il respecter des distances de sécurité spécifiques ?",
      'Est-il obligatoire de souscrire une assurance responsabilité civile spéciale pour cette journée ?',
      'Comment doit-on organiser le nettoyage de la rue à la fin de la fête pour laisser les lieux impeccables ?',
      "Pouvez-vous me mettre en relation avec d'autres organisateurs de fêtes de quartier pour partager leurs astuces ?",
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-16',
    category: 'Voyages',
    title: 'Forfait voyage en agence pour les îles de la Madeleine',
    scenario:
      'Vous rêvez de visiter les îles de la Madeleine cet été. Vous vous rendez dans une agence de voyages pour concevoir un séjour sur mesure.',
    examinerRole: "L'agent de voyages spécialisé dans les destinations canadiennes.",
    examineeRole: 'Le client qui planifie son voyage estival.',
    instructions:
      'Posez des questions sur les modes de transport (avion, traversier), la location de voiture sur place, les hébergements typiques et le budget global.',
    suggestedQuestions: [
      "Bonjour, quelle est la meilleure période de l'été pour visiter les îles de la Madeleine sans foule excessive ?",
      "Conseillez-vous plutôt d'y aller en avion direct ou en traversier avec notre propre véhicule depuis l'Île-du-Prince-Édouard ?",
      'Est-il facile de louer une voiture une fois sur place ou les véhicules sont-ils rapidement en rupture de stock ?',
      "Quels types d'hébergement proposez-vous : plutôt des auberges chaleureuses, des chalets côtiers ou des hôtels ?",
      "Quelles sont les excursions incontournables à ne pas manquer, comme l'observation des falaises ou les ateliers de fumage de poisson ?",
      "Proposez-vous des forfaits complets incluant les billets, l'hébergement, la voiture et certaines activités guidées ?",
      "À combien s'élève le budget approximatif par personne pour un séjour d'une semaine complète ?",
      'Quelles assurances annulation et rapatriement me recommandez-vous de souscrire pour ce voyage insulaire ?',
      'Quelles sont les conditions météorologiques habituelles et quel genre de vêtements chauds faut-il prévoir même en été ?',
      "Jusqu'à quelle date puis-je réserver pour bénéficier des meilleurs tarifs aériens et hôteliers ?",
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-17',
    category: 'Équipement de plein air',
    title: 'Achat de matériel de camping quatre saisons',
    scenario:
      'Vous préparez vos premières sorties de camping automnales et hivernales. Vous demandez conseil à un vendeur en magasin de sport spécialisé.',
    examinerRole: 'Le conseiller technique en équipement de plein air.',
    examineeRole: "L'acheteur qui veut investir dans du matériel durable et chaud.",
    instructions:
      "Renseignez-vous sur la cote thermique des sacs de couchage, la résistance au vent des tentes, les réchauds d'hiver et le poids de portage.",
    suggestedQuestions: [
      'Bonjour, quelle est la différence majeure entre une tente trois saisons et une tente quatre saisons pour le vent et la neige ?',
      "Quel indice de température minimale recommandez-vous pour un sac de couchage destiné aux nuits d'automne en altitude ?",
      "Vaut-il mieux privilégier un garnissage en duvet naturel ou en fibres synthétiques pour résister à l'humidité ?",
      "Quelle est l'importance de la valeur R du matelas de sol isolant pour ne pas perdre sa chaleur par conduction ?",
      'Quel type de réchaud fonctionne de manière fiable lorsque les températures descendent sous le point de congélation ?',
      'Combien pèse au total cet ensemble de bivouac et est-il facile à compacter dans un sac de soixante litres ?',
      "Les toiles de tente sont-elles garanties contre les déchirures et vendez-vous des trousses de réparation d'urgence ?",
      'Avez-vous des conseils pour entretenir et aérer son sac de couchage après chaque expédition ?',
      "Offrez-vous une politique de retour ou d'échange si le matériel ne convient pas après un premier essai sur le terrain ?",
      'Proposez-vous des rabais pour les membres ou lors des promotions saisonnières de fin de série ?',
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-18',
    category: 'Environnement',
    title: 'Adhésion à un jardin collectif municipal',
    scenario:
      "Vous voulez cultiver vos propres légumes bio et vous rencontrez le responsable de l'association du jardin partagé de votre quartier.",
    examinerRole: "Le président de l'association du jardin collectif.",
    examineeRole: 'Le citoyen qui souhaite obtenir une parcelle.',
    instructions:
      "Interrogez l'examinateur sur les listes d'attente, les corvées obligatoires, l'eau d'arrosage, l'interdiction des pesticides et la cotisation annuelle.",
    suggestedQuestions: [
      "Bonjour, comment fonctionne l'attribution des parcelles de culture dans votre jardin communautaire ?",
      "Y a-t-il une liste d'attente et quel est le délai moyen pour obtenir un lopin de terre ?",
      'Quelle est la surface moyenne accordée à chaque jardinier pour ses plantations de légumes ?',
      "Quelles sont les obligations de participation bénévole pour l'entretien des espaces et clôtures partagés ?",
      "L'accès à l'eau pour l'arrosage est-il disponible à volonté ou utilisez-vous des récupérateurs d'eau de pluie ?",
      "Quels types d'engrais et de produits de traitement sont strictement interdits pour respecter la charte biologique ?",
      'Fournissez-vous des outils collectifs comme des brouettes, des pelles et des arrosoirs dans un cabanon commun ?',
      "Organisez-vous des ateliers d'apprentissage pour les novices en permaculture et en compostage ?",
      "À combien s'élève le montant annuel de la cotisation d'adhésion par membre ?",
      "Quels sont les horaires d'ouverture et d'accès au jardin au cours des différentes saisons de l'année ?",
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-19',
    category: 'Transports actifs',
    title: "Préparation d'un vélo pour l'hiver en atelier",
    scenario: "Vous voulez continuer à vous déplacer à vélo malgré la neige et le sel. Vous vous renseignez auprès d'un mécanicien cycle.",
    examinerRole: "Le mécanicien d'un atelier de réparation de vélos.",
    examineeRole: "Le cycliste urbain qui souhaite équiper son vélo pour l'hiver.",
    instructions:
      'Posez des questions sur les pneus à clous, la protection de la chaîne contre la rouille, les freins, le délai de révision et le coût estimé.',
    suggestedQuestions: [
      "Bonjour, quels sont les aménagements indispensables pour rouler à vélo en toute sécurité durant l'hiver québécois ?",
      "Recommandez-vous d'installer des pneus avec des clous en carbure ou des pneus d'hiver à gomme tendre suffisent-ils ?",
      'Comment protéger efficacement la chaîne et le dérailleur contre la corrosion agressive causée par le sel de déglaçage ?',
      'Les freins sur jante classiques fonctionnent-ils bien sous la neige fondante ou vaut-il mieux des freins à disque ?',
      "Quel type d'huile ou de lubrifiant spécial basse température faut-il appliquer sur la transmission en saison froide ?",
      "Quels garde-boue me conseillez-vous pour éviter d'être aspergé de gadoue sur le chemin du travail ?",
      "Quels systèmes d'éclairage puissant et catadioptres obligatoires préconisez-vous face à la noirceur précoce ?",
      'Quel est le délai nécessaire pour effectuer une mise au point hivernale complète dans votre atelier ?',
      "Combien coûte le forfait complet incluant la main-d'œuvre, les deux pneus cloutés et le nettoyage minutieux ?",
      'Offrez-vous un service de vérification rapide de la pression des pneus et de graissage gratuit pendant la saison ?',
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
  {
    id: 'eo-t2-20',
    category: 'Natation',
    title: 'Cours de perfectionnement en natation pour adultes',
    scenario:
      "Vous souhaitez perfectionner votre technique de crawl et d'endurance. Vous rencontrez le responsable des activités aquatiques à la piscine municipale.",
    examinerRole: 'Le maître-nageur coordonnateur de la piscine municipale.',
    examineeRole: "L'adulte désirant perfectionner sa technique de nage.",
    instructions:
      'Renseignez-vous sur les créneaux horaires, les groupes de niveau, les maîtres-nageurs, le port du bonnet et les tarifs résidents.',
    suggestedQuestions: [
      'Bonjour, proposez-vous des cours de natation spécifiquement conçus pour les adultes de niveau intermédiaire ?',
      "Quels sont les jours et heures proposés pour les séances d'entraînement le soir après dix-huit heures ?",
      "Comment évaluez-vous le niveau des participants pour s'assurer d'une homogénéité dans les couloirs de nage ?",
      'Quels styles de nage sont travaillés au cours de la session : principalement le crawl ou aussi le dos et la brasse ?',
      'Le port du bonnet de bain et de lunettes de natation est-il strictement obligatoire dans votre bassin ?',
      'Combien de nageurs au maximum sont inscrits par couloir de nage pour éviter de se gêner lors des séries ?',
      "Le bassin est-il de vingt-cinq ou cinquante mètres et quelle est la température habituelle de l'eau ?",
      'Y a-t-il des casiers sécurisés avec cadenas et des vestiaires individuels propres à disposition ?',
      'Quel est le tarif pour une session complète de dix cours de quarante-cinq minutes pour les résidents de la ville ?',
      'Est-il possible de récupérer une séance manquée en cas de maladie en venant sur un autre groupe dans la semaine ?',
    ],
    prepSeconds: 120,
    durationSeconds: 210,
    taskIndex: 2,
  },
]

export const TCF_SPEAKING_TASK3_PROMPTS: TcfSpeakingTask3Prompt[] = [
  {
    id: 'eo-t3-01',
    category: 'Mobilité et société',
    title: 'Faut-il rendre tous les transports en commun gratuits ?',
    topic: 'La gratuité totale des autobus, tramways et métros dans les grandes métropoles.',
    prompt:
      'De plus en plus de villes débattent de la gratuité des transports publics. Selon vous, est-ce une mesure efficace et juste ? Donnez votre opinion argumentée en pesant les avantages et les inconvénients.',
    suggestedArgumentsFor: [
      'Incitation écologique majeure à abandonner la voiture individuelle et réduire le smog',
      "Soutien direct et égalitaire au pouvoir d'achat des classes populaires et des étudiants",
      'Gain de temps et économie de gestion : plus de billets, de tourniquets ni de contrôleurs',
    ],
    suggestedArgumentsAgainst: [
      'Perte colossale de recettes financières nécessaires pour étendre et entretenir le réseau',
      'Risque de baisse de qualité, de propreté et de fréquence des passages si le budget public flanche',
      "L'enjeu premier des automobilistes est la ponctualité et la vitesse, pas nécessairement le coût du billet",
    ],
    sampleOutline: [
      'Introduction : poser le débat sur la mobilité urbaine et annoncer votre position nuancée',
      'Arguments favorables : justice sociale, transition énergétique et désengorgement routier',
      'Limites et réserves : coûts financiers pour les contribuables et impératif de fiabilité avant tout',
      'Votre avis personnel : tarification solidaire ciblée plutôt que gratuité aveugle, et investissements prioritaires',
      "Conclusion : synthèse et vision prospective d'une mobilité durable",
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-02',
    category: 'Éducation et jeunesse',
    title: "Interdiction des téléphones intelligents à l'école",
    topic: "L'interdiction stricte des cellulaires durant toute la journée scolaire pour les élèves.",
    prompt:
      'Plusieurs gouvernements bannissent totalement les téléphones des écoles secondaires. Que pensez-vous de cette mesure ? Partagez vos arguments pour ou contre cette interdiction.',
    suggestedArgumentsFor: [
      'Augmentation prouvée de la concentration en classe et baisse spectaculaire des distractions',
      'Réduction drastique du cyberharcèlement, des photos volées et des rumeurs dans les couloirs',
      'Retour des échanges humains réels, des jeux collectifs et du bavardage convivial pendant les pauses',
    ],
    suggestedArgumentsAgainst: [
      "Illusion de régler un problème de société en cachant l'outil au lieu d'éduquer au numérique",
      'Utilité pédagogique du téléphone pour des recherches rapides ou des projets interactifs guidés',
      "Difficulté pour les parents de joindre leur enfant en cas d'urgence après les cours",
    ],
    sampleOutline: [
      'Introduction : omniprésence des écrans chez les adolescents et problématique scolaire',
      "Pourquoi l'interdiction est salutaire : santé mentale, sanctuaire d'apprentissage et climat scolaire",
      'Les nuances à apporter : éducation aux médias nécessaire et exceptions médicales ou pédagogiques',
      "Votre point de vue personnel : fermeté dans l'établissement scolaire et responsabilité partagée avec les parents",
      "Conclusion : l'école doit protéger l'enfance tout en préparant à un usage éclairé",
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-03',
    category: 'Travail',
    title: 'La semaine de travail de 4 jours pour tous',
    topic: 'Passer à 32 heures de travail réparties sur 4 jours sans diminution de salaire.',
    prompt:
      'La semaine de quatre jours gagne en popularité à travers le monde. Est-ce une évolution souhaitable et viable du monde professionnel ? Exposez votre point de vue détaillé.',
    suggestedArgumentsFor: [
      'Amélioration majeure de la santé mentale des employés et réduction des arrêts maladie liés au surmenage',
      "Productivité souvent égale ou supérieure grâce à une concentration accrue et l'élimination des temps morts",
      'Attractivité formidable pour recruter des talents et fidéliser les équipes en poste',
    ],
    suggestedArgumentsAgainst: [
      'Inapplicabilité dans certains secteurs à présence continue (santé, éducation, police, hôtellerie)',
      "Risque d'intensification néfaste de la cadence pendant les 4 jours ouvrés",
      "Coûts supplémentaires insurmontables pour les très petites entreprises obligées d'embaucher",
    ],
    sampleOutline: [
      'Introduction : mutation du rapport au travail après la crise sanitaire',
      'Bénéfices évidents : bien-être individuel, vie de famille épanouie et efficience professionnelle',
      'Contraintes structurelles : disparités sectorielles et complexité de mise en œuvre',
      "Votre avis argumenté : encourager la formule avec flexibilité selon les secteurs d'activité",
      'Conclusion : redéfinir la valeur du travail par les résultats plutôt que par le temps passé au bureau',
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-04',
    category: 'Emploi et société',
    title: 'Le télétravail : progrès durable ou piège social ?',
    topic: 'Le travail à distance généralisé plusieurs jours par semaine.',
    prompt:
      "Certaines entreprises imposent le retour au bureau tandis que d'autres restent en télétravail complet. Quel est selon vous le modèle de travail idéal ? Justifiez votre vision.",
    suggestedArgumentsFor: [
      'Suppression des trajets stressants et polluants, gain de temps considérable au quotidien',
      "Meilleure autonomie dans l'organisation de son temps et équilibre personnel enrichi",
      'Possibilité pour les employés de vivre dans des régions plus abordables loin des métropoles',
    ],
    suggestedArgumentsAgainst: [
      "Isolement social, affaiblissement du sentiment d'appartenance à un collectif d'entreprise",
      'Difficulté à déconnecter le soir et frontière poreuse entre maison et emploi',
      'Complexité accrue pour former et intégrer les jeunes diplômés sans présence physique des aînés',
    ],
    sampleOutline: [
      'Introduction : la transformation radicale des habitudes de bureau depuis quelques années',
      'Les bienfaits indéniables du travail à domicile sur la qualité de vie et la productivité individuelle',
      "Les dangers insidieux : perte de culture d'entreprise, solitude et sédentarité accrue",
      'Votre proposition équilibrée : le modèle hybride (2 jours en équipe, 3 jours à domicile) comme juste milieu',
      'Conclusion : la confiance managériale comme clé du succès moderne',
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-05',
    category: 'Technologies et éthique',
    title: "L'essor de l'intelligence artificielle dans nos vies",
    topic: "L'automatisation et l'utilisation quotidienne d'outils d'intelligence artificielle générative.",
    prompt:
      "L'IA transforme les métiers et l'accès au savoir à une vitesse vertigineuse. Faut-il y voir une opportunité formidable ou un danger pour l'humain ? Développez votre réflexion.",
    suggestedArgumentsFor: [
      'Gains de temps prodigieux sur les tâches répétitives, calculs complexes et rédaction technique',
      'Accélération des découvertes scientifiques, médicales et solutions pour la transition énergétique',
      "Démocratisation d'outils d'apprentissage interactifs personnalisés accessibles à tous",
    ],
    suggestedArgumentsAgainst: [
      "Risque massif de destructions d'emplois qualifiés sans reconversion immédiate",
      'Atrophie de la pensée critique, de la créativité humaine et prolifération de fausses informations',
      'Questions éthiques graves sur la propriété intellectuelle et la surveillance algorithmique',
    ],
    sampleOutline: [
      "Introduction : définition de la révolution de l'IA et omniprésence soudaine de ces technologies",
      "Les opportunités exaltantes pour la science, la santé et l'efficacité des organisations",
      'Les périls à ne pas sous-estimer : dépendance cognitive, désinformation et enjeux démocratiques',
      "Votre positionnement : réguler fermement le déploiement de l'IA tout en formant les citoyens à son usage critique",
      "Conclusion : la technologie doit rester un instrument au service de l'homme, jamais son maître",
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-06',
    category: 'Environnement urbain',
    title: 'Interdire les véhicules thermiques dans les centres-villes',
    topic: 'La fermeture complète des centres urbains aux voitures à moteur thermique.',
    prompt:
      "Pour assainir l'air, plusieurs métropoles bannissent les voitures à essence de leurs rues centrales. Approuvez-vous cette orientation politique ? Donnez vos arguments.",
    suggestedArgumentsFor: [
      "Baisse immédiate de la pollution de l'air et diminution des maladies respiratoires chez les enfants",
      "Pacification de l'espace public, réappropriation des rues par les piétons, familles et cyclistes",
      'Dynamisation des commerces locaux et terrasses grâce à un environnement calme et agréable',
    ],
    suggestedArgumentsAgainst: [
      'Pénalisation injuste des habitants des banlieues éloignées sans alternative de transport décente',
      "Complexité majeure pour les artisans, livreurs et personnes handicapées dépendantes d'un véhicule",
      'Report de la congestion et de la pollution vers les quartiers périphériques résidentiels',
    ],
    sampleOutline: [
      "Introduction : le défi climatique urbain et la place démesurée de l'automobile en ville",
      'Les arguments de santé publique et de sécurité justifiant la piétonnisation des centres',
      "Les risques d'exclusion sociale des banlieusards et les contraintes logistiques du commerce",
      'Votre avis constructif : interdire progressivement mais en développant massivement parkings relais et transports',
      'Conclusion : inventer une ville respirable sans fracturer les liens avec sa périphérie',
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-07',
    category: 'Économie et consommation',
    title: "Le commerce en ligne menace-t-il l'âme de nos quartiers ?",
    topic: "L'hégémonie des plateformes d'achat en ligne face aux boutiques indépendantes physiques.",
    prompt:
      'Acheter en un clic sur Internet est devenu un réflexe. Les petits commerces de proximité sont-ils condamnés à disparaître ? Exposez votre analyse et vos solutions.',
    suggestedArgumentsFor: [
      'Confort inégalable pour comparer les prix, commander à toute heure et recevoir chez soi',
      'Accès à une gamme infinie de produits indisponibles dans les petites villes de région',
      'Gain de temps précieux pour les personnes à mobilité réduite ou aux horaires décalés',
    ],
    suggestedArgumentsAgainst: [
      'Désertification dramatique des rues commerçantes et fermeture de librairies et commerces historiques',
      'Pollution massive par les emballages carton et le ballet incessant des camionnettes de livraison',
      'Perte irremplaçable du contact humain, des conseils personnalisés et de la vie de quartier',
    ],
    sampleOutline: [
      "Introduction : la transformation radicale de nos modes d'achat depuis deux décennies",
      'Pourquoi le commerce en ligne a conquis les consommateurs : praticité, choix et économies',
      'Le coût invisible pour la collectivité : perte de lien social, fermetures de rideaux et pollution',
      'Votre point de vue : encourager la complémentarité par le commerce local en ligne et le soutien public',
      'Conclusion : consommer est un acte citoyen qui façonne le visage de nos villes',
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-08',
    category: 'Alimentation et climat',
    title: 'Faut-il réduire notre consommation de viande ?',
    topic: "L'impact de l'élevage intensif et l'adoption d'un régime alimentaire végétalisé.",
    prompt:
      'Faut-il inciter les citoyens à réduire drastiquement leur consommation de viande pour sauver le climat ? Présentez votre argumentation personnelle.',
    suggestedArgumentsFor: [
      "L'élevage bovin est l'une des sources majeures d'émissions de gaz à effet de serre et de déforestation",
      "Bénéfices démontrés pour la santé cardiovasculaire d'un régime riche en végétaux et légumineuses",
      "Question éthique du bien-être animal et des conditions inacceptables de l'élevage industriel",
    ],
    suggestedArgumentsAgainst: [
      'La viande apporte des protéines complètes, du fer assimilable et de la vitamine B12 indispensables',
      "Importance économique et patrimoniale de l'élevage paysan pour l'entretien des paysages ruraux",
      "Refus d'une culpabilisation morale des mangeurs et respect des traditions culinaires familiales",
    ],
    sampleOutline: [
      "Introduction : l'empreinte environnementale de notre assiette au cœur des débats écologiques",
      "Les données scientifiques sans appel : climat, biodiversité et consommation d'eau de l'élevage",
      'Les nuances légitimes : santé nutritionnelle, viabilité des terroirs et plaisirs gastronomiques',
      'Votre avis équilibré : le flexitarisme (manger moins de viande, mais locale et biologique) comme solution pragmatique',
      "Conclusion : une transition alimentaire progressive guidée par l'éducation plutôt que par l'interdiction",
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-09',
    category: 'Tourisme et environnement',
    title: "Surtourisme : faut-il restreindre l'accès aux sites naturels ?",
    topic: "La mise en place de quotas et de réservations payantes dans les parcs et lieux d'exception.",
    prompt:
      "Certains parcs nationaux et sites historiques saturent sous l'afflux des visiteurs. Faut-il limiter le nombre d'entrées ? Défendez votre opinion.",
    suggestedArgumentsFor: [
      "Protection vitale de la faune, de la flore et des sentiers fragilisés par l'érosion",
      'Expérience de visite préservée dans le calme et la contemplation sans foule oppressante',
      "Sécurité renforcée et réduction de l'accumulation des déchets abandonnés",
    ],
    suggestedArgumentsAgainst: [
      'La nature est un bien commun qui devrait rester accessible librement à chaque être humain',
      "Risque d'exclusion des personnes peu connectées ou incapables de planifier des mois à l'avance",
      'Impact économique négatif pour les hôteliers et commerçants des régions touristiques dépendantes',
    ],
    sampleOutline: [
      'Introduction : le phénomène mondial du tourisme de masse amplifié par les réseaux sociaux',
      'La nécessité écologique impérative de protéger les écosystèmes vulnérables de la surfréquentation',
      "Les risques d'élitisme et d'inégalité d'accès aux trésors du patrimoine naturel",
      'Votre recommandation : des quotas équitables avec des plages réservées aux résidents et aux écoles',
      'Conclusion : apprendre à contempler le monde avec humilité et respect de sa fragilité',
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-10',
    category: 'Économie et liberté',
    title: "Vers la fin de l'argent liquide : progrès ou surveillance ?",
    topic: 'La disparition programmée des pièces et billets de banque au profit des cartes et téléphones.',
    prompt:
      "Dans plusieurs pays, presque tous les paiements sont électroniques. L'éradication du cash est-elle un progrès ? Exprimez votre point de vue argumenté.",
    suggestedArgumentsFor: [
      'Simplicité, rapidité et hygiène des paiements sans contact au quotidien',
      "Arme redoutable contre l'évasion fiscale, le vol à la tire et les trafics clandestins",
      'Coût élevé de transport et de sécurité des billets physiques évité pour les commerçants',
    ],
    suggestedArgumentsAgainst: [
      "Disparition totale de l'anonymat financier et surveillance généralisée de chaque dépense privée",
      'Vulnérabilité absolue en cas de panne de réseau électrique ou de cyberattaque bancaire',
      'Exclusion cruelle des sans-abri, des aînés et des personnes en situation de précarité bancaire',
    ],
    sampleOutline: [
      'Introduction : la transition accélérée vers une économie dématérialisée',
      "Les avantages incontestables en matière d'efficacité moderne et de transparence fiscale",
      "Les menaces liberticides sur la vie privée et les risques techniques d'une société sans secours physique",
      'Votre jugement : maintenir le liquide comme option légale obligatoire pour garantir la liberté individuelle',
      "Conclusion : l'innovation monétaire ne doit jamais sacrifier la résilience démocratique",
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-11',
    category: 'Éducation',
    title: "L'uniforme obligatoire à l'école publique",
    topic: "L'imposition d'une tenue scolaire unique pour tous les élèves du primaire et secondaire.",
    prompt:
      "L'instauration de l'uniforme revient régulièrement dans l'actualité éducative. Est-ce une bonne idée pour favoriser l'égalité à l'école ? Présentez votre argumentation.",
    suggestedArgumentsFor: [
      'Atténuation visuelle des disparités sociales et arrêt de la surenchère des marques coûteuses',
      "Renforcement du sentiment d'appartenance à une communauté d'apprentissage unie",
      'Gain de temps et sérénité le matin pour les parents et les élèves',
    ],
    suggestedArgumentsAgainst: [
      "Entrave à la liberté d'expression individuelle et à la construction de la personnalité des jeunes",
      'Mesure superficielle qui ne règle pas le harcèlement scolaire sur le fond',
      'Coût financier supplémentaire non négligeable pour les familles modestes',
    ],
    sampleOutline: [
      "Introduction : les défis d'égalité et de climat scolaire dans les écoles publiques",
      "Les arguments en faveur de l'uniforme : cohésion, discipline et égalité des apparences",
      "Les critiques légitimes : uniformisation artificielle et déplacement des tensions vers d'autres objets",
      "Votre position : l'égalité se construit par l'accompagnement pédagogique plutôt que par le vêtement",
      "Conclusion : l'école doit apprendre à vivre harmonieusement dans la diversité réelle",
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-12',
    category: 'Santé publique',
    title: 'Taxer la malbouffe pour financer la santé',
    topic: "L'instauration d'une taxe nutritionnelle lourde sur les boissons gazeuses et aliments ultra-transformés.",
    prompt:
      "Faut-il surtaxer les produits trop sucrés, gras ou salés pour lutter contre l'obésité et financer les hôpitaux ? Développez vos arguments.",
    suggestedArgumentsFor: [
      'Pression financière directe sur les multinationales agroalimentaires pour améliorer leurs recettes',
      'Baisse mesurée de la consommation de sucre chez les jeunes dans les pays ayant testé la taxe',
      'Recettes fiscales précieuses réinvesties dans le système de santé publique sous pression',
    ],
    suggestedArgumentsAgainst: [
      'Taxe régressive qui frappe de plein fouet les familles modestes dont le budget alimentaire est serré',
      "Risque d'infantilisation des citoyens et atteinte à la liberté de choix alimentaire",
      "Inefficacité si elle n'est pas accompagnée d'un accès subventionné à des aliments sains",
    ],
    sampleOutline: [
      'Introduction : la crise sanitaire des maladies chroniques liées à la mauvaise alimentation',
      'Pourquoi la taxe comportementale est un levier efficace : incitation des industriels et rentrées de fonds',
      "Les limites éthiques et sociales : risque d'injustice économique pour les foyers précaires",
      'Votre proposition globale : taxer la malbouffe tout en subventionnant les fruits et légumes biologiques',
      'Conclusion : la santé publique exige un environnement alimentaire protecteur et éducatif',
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-13',
    category: 'Société et loisirs',
    title: 'Le travail du dimanche : liberté ou régression sociale ?',
    topic: "L'autorisation d'ouverture des commerces de détail tous les dimanches de l'année.",
    prompt:
      'Travailler ou faire ses courses le dimanche est-il un progrès pour les consommateurs ou un recul pour la vie de famille ? Exposez vos arguments.',
    suggestedArgumentsFor: [
      "Liberté totale pour les citoyens d'organiser leur emploi du temps selon leurs contraintes personnelles",
      "Création d'opportunités d'emplois étudiants rémunérés avec majoration salariale",
      'Dynamisme commercial accru face à la concurrence des sites de vente en ligne ouverts 24h/24',
    ],
    suggestedArgumentsAgainst: [
      'Destruction du temps de repos synchronisé indispensable à la cohésion familiale et amicale',
      'Pression exercée sur les employés vulnérables qui ne peuvent pas toujours refuser de travailler',
      "Banalisation d'un mode de vie entièrement axé sur la consommation matérielle continue",
    ],
    sampleOutline: [
      'Introduction : la place du repos collectif dans une société de plus en plus trépidante',
      'Les arguments économiques de flexibilité et de réponse aux attentes des consommateurs urbains',
      'Les conséquences humaines néfastes sur la santé mentale, la parentalité et les engagements associatifs',
      'Votre avis affirmé : sanctuariser le dimanche comme journée de pause et de loisirs communs',
      "Conclusion : l'équilibre d'une société ne se mesure pas à ses heures d'ouverture commerciales",
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-14',
    category: 'Logement urbain',
    title: 'La crise du logement et les locations touristiques Airbnb',
    topic: 'La prolifération des meublés de tourisme dans les centres-villes résidentiels.',
    prompt:
      "Les plateformes de location courte durée sont souvent accusées d'aggraver la pénurie de logements locatifs. Faut-il les interdire ou les encadrer sévèrement ? Donnez votre avis.",
    suggestedArgumentsFor: [
      'Droit légitime des propriétaires de disposer de leur bien pour compléter leurs revenus face aux hausses de taux',
      'Diversification des hébergements touristiques permettant aux voyageurs de vivre dans de vrais quartiers',
      'Retombées économiques positives pour les restaurants et commerçants hors des zones hôtelières',
    ],
    suggestedArgumentsAgainst: [
      'Retrait massif de milliers de logements du marché locatif régulier, provoquant une flambée des loyers',
      "Désertification des quartiers centraux transformés en parcs d'attractions touristiques éphémères",
      "Nuisances sonores et incivilités répétées pour les voisins résidents dans les immeubles d'habitation",
    ],
    sampleOutline: [
      "Introduction : l'ampleur de la crise du logement dans les grandes métropoles canadiennes et mondiales",
      "Les promesses initiales de l'économie de partage et les bénéfices pour certains propriétaires",
      "La réalité spéculative dévastatrice : rachat d'immeubles complets et évictions de locataires vulnérables",
      'Votre positionnement : limiter strictement la location à la résidence principale quelques semaines par an',
      "Conclusion : le logement doit demeurer un droit fondamental avant d'être une opportunité spéculative",
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-15',
    category: 'Jeunesse et travail',
    title: "Faut-il interdire les stages d'études non rémunérés ?",
    topic: "L'obligation légale de verser un salaire décent à tout stagiaire dès le premier jour.",
    prompt:
      'De nombreux étudiants effectuent encore des stages obligatoires sans recevoir un sou. Est-ce acceptable au nom de la formation ? Prenez position avec des arguments convaincants.',
    suggestedArgumentsFor: [
      'Rémunérer tout travail est un principe de justice sociale et de dignité fondamentale',
      'Les stages non payés excluent les étudiants défavorisés incapables de subvenir à leurs besoins sans salaire',
      "Mettre fin à l'abus d'employeurs qui remplacent des postes salariés permanents par des stagiaires précaires",
    ],
    suggestedArgumentsAgainst: [
      "Les organismes sans but lucratif et petites structures culturelles n'ont pas les moyens de payer les stagiaires",
      "Le stagiaire est avant tout en position d'apprenant qui mobilise du temps et de l'encadrement de l'équipe",
      "Risque de diminution drastique des opportunités d'observation et de découverte pour les jeunes",
    ],
    sampleOutline: [
      'Introduction : la précarité croissante de la jeunesse étudiante et le rôle des stages obligatoires',
      'Pourquoi le travail non rémunéré est une aberration sociale qui creuse les inégalités de départ',
      'Les difficultés réelles des OBNL et la distinction entre observation brève et véritable travail de production',
      'Votre proposition : subventionner les stages associatifs par des fonds publics pour payer chaque étudiant',
      'Conclusion : investir dans la jeunesse commence par reconnaître la valeur de son travail',
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-16',
    category: 'Climat et transport',
    title: "L'avion face à l'urgence climatique : faut-il restreindre les vols ?",
    topic: "La mise en place de quotas de vols, de taxes massives sur le kérosène ou l'interdiction des vols courts.",
    prompt:
      "L'avion est le mode de transport le plus polluant par passager. Doit-on limiter les voyages aériens par des mesures contraignantes ? Développez votre réflexion.",
    suggestedArgumentsFor: [
      "L'aviation commerciale contribue lourdement au réchauffement et profite à une minorité de la population mondiale",
      "L'interdiction des vols intérieurs courts stimule l'usage et la modernisation du réseau ferroviaire",
      'Nécessité de modérer nos modes de vie pour respecter les engagements climatiques internationaux',
    ],
    suggestedArgumentsAgainst: [
      "Entrave inacceptable à la liberté de voyager, de découvrir d'autres cultures et d'ouvrir son esprit",
      "Isolement des familles d'immigrants et des diasporas séparées de leurs proches par des océans",
      'Catastrophe économique pour les nations insulaires et les régions éloignées sans alternative ferroviaire',
    ],
    sampleOutline: [
      "Introduction : le paradoxe entre le désir d'explorer le monde et l'urgence de protéger la planète",
      "Les arguments scientifiques en faveur d'un freinage immédiat des émissions issues de l'aviation",
      "Les impacts humains et sociaux d'une restriction brutale pour les familles transnationales",
      'Votre point de vue nuancé : supprimer les vols courts remplacés par le train et taxer lourdement les jets privés',
      'Conclusion : inventer un tourisme plus lent, plus proche et plus respectueux de notre maison commune',
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-17',
    category: 'Sécurité routière',
    title: 'Âge légal du permis de conduire : 16 ou 18 ans ?',
    topic: "Le relèvement ou le maintien de l'âge minimum requis pour obtenir le permis de conduire automobile.",
    prompt:
      'Dans certaines provinces, on peut conduire dès seize ans. Faut-il repousser cet âge à dix-huit ans pour réduire les accidents ? Justifiez votre position.',
    suggestedArgumentsFor: [
      'Le cerveau des adolescents de 16 ans est plus enclin aux prises de risques inconsidérées et aux distractions',
      "Statistiques d'accidentalité routière nettement plus élevées chez les très jeunes conducteurs débutants",
      "Incitation salutaire à utiliser les transports collectifs et les mobilités actives durant l'adolescence",
    ],
    suggestedArgumentsAgainst: [
      'La voiture est indispensable pour travailler ou étudier dans les zones rurales mal desservies par les bus',
      "L'apprentissage précoce encadré permet d'acquérir de l'expérience sous la supervision des parents",
      "Accroissement de l'autonomie et responsabilisation des jeunes adultes prêts à entrer sur le marché de l'emploi",
    ],
    sampleOutline: [
      "Introduction : la conduite automobile comme rite de passage vers l'âge adulte",
      'Les arguments de sécurité routière justifiant une maturité plus élevée pour manier un véhicule lourd',
      "Les réalités géographiques des régions où l'absence de voiture condamne à l'immobilité complète",
      'Votre avis équilibré : maintenir à 16 ans avec un permis progressif très strict (tolérance zéro alcool, pas de nuit)',
      "Conclusion : l'encadrement rigoureux de l'apprentissage est plus efficace que l'interdiction pure et simple",
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-18',
    category: 'Démocratie et technologie',
    title: 'Le vote électronique aux élections générales',
    topic: "Remplacer l'urne et le bulletin papier par le vote en ligne depuis son domicile.",
    prompt:
      'Voter depuis son canapé sur son téléphone portable pourrait relancer la participation électorale. Est-ce une bonne chose pour la démocratie ? Donnez votre avis.',
    suggestedArgumentsFor: [
      'Hausse attendue de la participation citoyenne, en particulier chez les jeunes et les personnes empêchées',
      "Rapidité et économies majeures sur l'impression de bulletins papier et le dépouillement manuel",
      "Facilité d'accès pour les expatriés et les citoyens vivant dans des régions très isolées",
    ],
    suggestedArgumentsAgainst: [
      'Vulnérabilité face aux cyberattaques étrangères, aux piratages de serveurs et aux fraudes invisibles',
      "Impossibilité de garantir le secret absolu du vote si l'électeur est sous la pression d'un proche à la maison",
      "Perte du rituel civique républicain de l'isoloir qui rassemble physiquement la communauté politique",
    ],
    sampleOutline: [
      "Introduction : l'abstention électorale croissante et la tentation de la solution technologique en ligne",
      "Les atouts de modernité et d'accessibilité universelle du vote par Internet",
      'Les risques mortels pour la confiance démocratique : failles informatiques et opacité des algorithmes',
      "Votre conviction ferme : le bulletin papier dans l'urne transparente reste le gage suprême de l'intégrité civique",
      'Conclusion : la démocratie exige un acte conscient et vérifiable par chaque citoyen sans intermédiaire technique',
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-19',
    category: 'Environnement visuel',
    title: "Bannir la publicité commerciale de l'espace public",
    topic: "L'interdiction totale des panneaux publicitaires géants et écrans vidéo dans les rues.",
    prompt:
      "La publicité commerciale envahit nos trottoirs et façades urbaines. Doit-on l'interdire dans l'espace public ? Argumentez votre position.",
    suggestedArgumentsFor: [
      'Préservation du paysage urbain, de la beauté architecturale et apaisement de la charge mentale des passants',
      'Arrêt des incitations permanentes à la surconsommation superflue et polluante',
      "Économie d'énergie substantielle en éteignant les écrans vidéo lumineux nocturnes",
    ],
    suggestedArgumentsAgainst: [
      'Pertes de revenus considérables pour les villes qui financent ainsi les abribus et le mobilier urbain',
      "Rôle d'information sur les produits, les créations culturelles et les événements locaux de proximité",
      'Soutien vital à la visibilité des petites et moyennes entreprises face aux géants du web',
    ],
    sampleOutline: [
      'Introduction : la saturation visuelle des citadins confrontés à des milliers de messages publicitaires par jour',
      "Pourquoi l'espace public doit redevenir un bien commun débarrassé des sollicitations marchandes agressives",
      'Les contre-arguments économiques liés au financement des équipements municipaux par les régies',
      "Votre proposition raisonnée : interdire les panneaux lumineux et numériques tout en gardant l'affichage culturel local",
      'Conclusion : redonner aux citoyens le droit à un environnement urbain serein et non marchandisé',
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
  {
    id: 'eo-t3-20',
    category: 'Monde du travail',
    title: 'Le retour obligatoire au bureau est-il une erreur managériale ?',
    topic: "L'obligation imposée par les directions de revenir travailler sur place 4 ou 5 jours par semaine.",
    prompt:
      'De nombreux dirigeants somment leurs employés de revenir au bureau à temps plein sous peine de licenciement. Partagez votre analyse de cette situation conflictuelle.',
    suggestedArgumentsFor: [
      "Renforcement indispensable de la culture d'entreprise, de la loyauté et de l'esprit de corps",
      "Facilité accrue de coordination spontanée, d'échanges informels et d'innovation collective en personne",
      'Meilleur accompagnement et transmission des savoirs auprès des nouvelles recrues et stagiaires',
    ],
    suggestedArgumentsAgainst: [
      'Régression managériale fondée sur la méfiance et la surveillance physique des salariés',
      "Perte d'un temps précieux dans les transports en commun, stress accru et démissions en cascade des meilleurs talents",
      "Non-prise en compte des gains avérés d'efficacité et de concentration lors des journées à domicile",
    ],
    sampleOutline: [
      'Introduction : le bras de fer actuel entre dirigeants conservateurs et salariés attachés à leur autonomie',
      'Les motivations réelles des directions : peur de perdre le contrôle et rentabilisation des baux immobiliers',
      'Les dégâts sur le climat social : perte de motivation, démissions et dégradation de la conciliation travail-famille',
      "Votre vision du management d'avenir : la flexibilité négociée avec des objectifs clairs plutôt que le présentéisme forcé",
      "Conclusion : l'avenir appartient aux entreprises qui bâtissent des relations de travail fondées sur la confiance",
    ],
    prepSeconds: 0,
    durationSeconds: 270,
    taskIndex: 3,
  },
]

export const TCF_SPEAKING_PROMPTS_BY_TASK: {
  1: TcfSpeakingTask1Prompt[]
  2: TcfSpeakingTask2Prompt[]
  3: TcfSpeakingTask3Prompt[]
} = {
  1: TCF_SPEAKING_TASK1_PROMPTS,
  2: TCF_SPEAKING_TASK2_PROMPTS,
  3: TCF_SPEAKING_TASK3_PROMPTS,
}

export const ALL_TCF_SPEAKING_PROMPTS: TcfSpeakingPrompt[] = [
  ...TCF_SPEAKING_TASK1_PROMPTS,
  ...TCF_SPEAKING_TASK2_PROMPTS,
  ...TCF_SPEAKING_TASK3_PROMPTS,
]
