// Offline French dictionary. Data is generated by scripts/build-dictionary.mjs into public/lexicon/fr
// and fetched one two-letter shard at a time.

import { playFrenchVoice } from './frenchVoice'

export type DictionaryEntry = {
  pos: string
  ipa: string
  gender: '' | 'm' | 'f' | 'mf'
  en: string[]
  zh: string[]
}

export type DictionaryWord = {
  word: string
  /** Meanings from this project's own curated word lists, when the word is in one. */
  site: string[]
  entries: DictionaryEntry[]
}

export type DictionaryResult = {
  query: string
  /** Direct matches for the query. */
  words: DictionaryWord[]
  /** Dictionary forms the query is an inflection of, e.g. mangeais → manger. */
  lemmas: DictionaryWord[]
}

type RawEntry = [pos: string, ipa: string, gender: DictionaryEntry['gender'], en: string[], zh: string[]]
type Shard = { e: Record<string, RawEntry[]>; s: Record<string, string[]>; f: Record<string, string[]> }

const EMPTY_SHARD: Shard = { e: {}, s: {}, f: {} }
const ELISIONS = /^(?:l|d|j|n|s|m|t|c|qu|jusqu|lorsqu|puisqu)'(?=.)/

export const POS_LABELS: Record<string, string> = {
  noun: '名词',
  verb: '动词',
  adj: '形容词',
  adv: '副词',
  prep: '介词',
  conj: '连词',
  pron: '代词',
  det: '限定词',
  article: '冠词',
  num: '数词',
  intj: '感叹词',
  phrase: '短语',
  prep_phrase: '介词短语',
  proverb: '谚语',
  contraction: '缩合词',
  particle: '小品词',
}

export const GENDER_LABELS: Record<DictionaryEntry['gender'], string> = { '': '', m: '阳性', f: '阴性', mf: '阴阳同形' }

/** Must stay in sync with `normalizeKey` in scripts/build-dictionary.mjs. */
export const normalizeDictionaryKey = (word: string) =>
  word.toLowerCase().replace(/œ/g, 'oe').replace(/æ/g, 'ae').normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[’`]/g, "'").trim()

/** Must stay in sync with `shardOf` in scripts/build-dictionary.mjs. */
export const dictionaryShard = (word: string) => {
  const key = normalizeDictionaryKey(word)
  return [key[0], key[1]].map((char) => (char && /[a-z]/.test(char) ? char : '_')).join('')
}

const shardCache = new Map<string, Promise<Shard>>()

function loadShard(name: string): Promise<Shard> {
  let pending = shardCache.get(name)
  if (!pending) {
    // Same deploy-prefix rule as the word-list fetcher.
    pending = fetch(`${REACT_APP_DEPLOY_ENV === 'pages' ? '/qwerty-learner' : ''}/lexicon/fr/${name}.json`)
      .then(async (response) => {
        // A missing shard just means no word starts with those letters. Static hosts answer it with a 404,
        // single-page fallbacks with an HTML page.
        if (response.status === 404) return EMPTY_SHARD
        if (!response.ok) throw new Error(`词典数据加载失败（${response.status}）`)
        if (!(response.headers.get('content-type') ?? '').includes('json')) return EMPTY_SHARD
        return (await response.json()) as Shard
      })
      .catch((error) => {
        shardCache.delete(name)
        throw error
      })
    shardCache.set(name, pending)
  }
  return pending
}

const toWord = (shard: Shard, word: string): DictionaryWord => ({
  word,
  site: shard.s[word] ?? [],
  entries: (shard.e[word] ?? []).map(([pos, ipa, gender, en, zh]) => ({ pos, ipa, gender, en, zh })),
})

/** Keys of `record` equal to `query` exactly, else ignoring case, else ignoring accents too. */
function matchKeys(record: Record<string, unknown>, query: string): string[] {
  if (query in record) return [query]
  const lower = query.toLowerCase()
  if (lower in record) return [lower]
  const normalized = normalizeDictionaryKey(query)
  return Object.keys(record).filter((key) => normalizeDictionaryKey(key) === normalized)
}

async function lookupExact(query: string): Promise<DictionaryResult> {
  const shard = await loadShard(dictionaryShard(query))
  const direct = Array.from(new Set([...matchKeys(shard.e, query), ...matchKeys(shard.s, query)]))
  const words = direct.map((word) => toWord(shard, word))

  const lemmaNames = new Set(matchKeys(shard.f, query).flatMap((form) => shard.f[form]))
  direct.forEach((word) => lemmaNames.delete(word))
  const lemmas = (
    await Promise.all(
      Array.from(lemmaNames)
        .slice(0, 4)
        .map(async (lemma) => {
          const lemmaShard = await loadShard(dictionaryShard(lemma))
          return lemma in lemmaShard.e ? toWord(lemmaShard, lemma) : null
        }),
    )
  ).filter((item): item is DictionaryWord => item !== null)

  return { query, words, lemmas }
}

export const cleanDictionaryQuery = (text: string) =>
  text
    .replace(/[’`]/g, "'")
    .replace(/^[\s.,;:!?«»"“”()[\]…—–-]+|[\s.,;:!?«»"“”()[\]…—–-]+$/g, '')
    .replace(/\s+/g, ' ')

export async function lookupDictionary(text: string): Promise<DictionaryResult> {
  const query = cleanDictionaryQuery(text)
  if (!query) return { query, words: [], lemmas: [] }
  const result = await lookupExact(query)
  if (result.words.length || result.lemmas.length) return result
  // l'école → école, qu'il → il
  const stripped = query.replace(ELISIONS, '')
  if (stripped !== query) {
    const retry = await lookupExact(stripped)
    if (retry.words.length || retry.lemmas.length) return retry
  }
  // peut-on → peut, aujourd'hui is found directly, qu'est-ce → est
  const parts = stripped.split(/[-']/).filter((part) => part.length > 1)
  if (parts.length > 1) {
    for (const part of [...parts].sort((a, b) => b.length - a.length)) {
      const retry = await lookupExact(part)
      if (retry.words.length || retry.lemmas.length) return retry
    }
  }
  return result
}

/** Headwords starting with the typed prefix (accents and case ignored). */
export async function suggestDictionaryWords(text: string, limit = 8): Promise<string[]> {
  const prefix = normalizeDictionaryKey(cleanDictionaryQuery(text))
  if (prefix.length < 2) return []
  const shard = await loadShard(dictionaryShard(prefix))
  const matches = new Set<string>()
  for (const key of [...Object.keys(shard.s), ...Object.keys(shard.e)]) {
    if (normalizeDictionaryKey(key).startsWith(prefix)) matches.add(key)
  }
  return Array.from(matches)
    .sort((a, b) => a.length - b.length || a.localeCompare(b, 'fr'))
    .slice(0, limit)
}

/** The shortest useful meaning for a word, preferring Chinese: used when saving a word to a word list. */
export function briefMeaning(result: DictionaryResult): string {
  const word = result.words[0] ?? result.lemmas[0]
  if (!word) return ''
  if (word.site.length) return word.site.join('；')
  const zh = word.entries.flatMap((entry) => entry.zh).slice(0, 3)
  if (zh.length) return zh.join('；')
  return word.entries
    .flatMap((entry) => entry.en)
    .slice(0, 2)
    .join('; ')
}

/** Find existing dictionary entries that differ from `text` by diacritics (e.g. ca → ça). */
export async function findAccentedVariants(text: string): Promise<string[]> {
  const query = cleanDictionaryQuery(text)
  const normalized = normalizeDictionaryKey(query)
  if (normalized.length < 2) return []
  const queryLower = query.toLowerCase()
  try {
    const shard = await loadShard(dictionaryShard(normalized))
    const allKeys = new Set([...Object.keys(shard.e), ...Object.keys(shard.s)])
    const seenLower = new Set<string>()
    const variants: string[] = []
    allKeys.forEach((key) => {
      const keyLower = key.toLowerCase()
      if (
        normalizeDictionaryKey(key) === normalized &&
        keyLower !== queryLower &&
        !seenLower.has(keyLower)
      ) {
        seenLower.add(keyLower)
        variants.push(key)
      }
    })
    return variants.slice(0, 5)
  } catch {
    return []
  }
}

export async function speakFrench(
  text: string,
  options?: { onStart?: () => void; onEnd?: () => void },
): Promise<boolean> {
  const cleaned = text.trim()
  if (!cleaned) return false
  try {
    const result = await playFrenchVoice(cleaned, options)
    if (result === 'played' || result === 'superseded') {
      return result === 'played'
    }
  } catch {
    // Fall back to speechSynthesis below
  }
  if (!('speechSynthesis' in window) || typeof SpeechSynthesisUtterance === 'undefined') {
    options?.onEnd?.()
    return false
  }
  const utterance = new SpeechSynthesisUtterance(cleaned)
  utterance.lang = 'fr-CA'
  utterance.rate = 0.9
  const onStart = options?.onStart
  if (onStart) utterance.onstart = () => onStart()
  const onEnd = options?.onEnd
  if (onEnd) {
    utterance.onend = () => onEnd()
    utterance.onerror = () => onEnd()
  }
  if (window.speechSynthesis.speaking || window.speechSynthesis.pending) {
    window.speechSynthesis.cancel()
  }
  window.speechSynthesis.speak(utterance)
  return true
}
